### ISSUE TITLE
'No module named onedrive

### ISSUE THREAD

**Issue by AxandrasGaming** [xybu/onedrive-d-old#109]
Hi,

thank you for this tool xybu.

I've got this error message when i execute : onedrive-d in console. Also the folders were not synchronized.

Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==0.85', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/daemon.py", line 169, in main
    quota = API.get_quota()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 626, in get_quota
    return op.itemgetter('available', 'quota')(super(OneDriveAPI, self).get_quota())
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 363, in get_quota
    return self('me/skydrive/quota')
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 355, in **call**
    self.auth_get_token()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 661, in auth_get_token
    ret = super(PersistentOneDriveAPI, self).auth_get_token(_argz, *_kwz)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 243, in auth_get_token
    res = self.auth_access_data_raw = self._auth_token_request()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 263, in _auth_token_request
    return self.request(self.auth_url_token, method='post', data=post_data)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 183, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (400, "400 Client Error: Bad Request [type: <class 'requests.exceptions.HTTPError'>, repr: HTTPError('400 Client Error: Bad Request',)]")
Exception ImportError: 'No module named onedrive' in <bound method PersistentOneDriveAPI.__del__ of <onedrive.api_v5.PersistentOneDriveAPI object at 0x7fddff8320d0>> ignored

best regards

Exar Kun

**Comment by xybu** [comment]
Why is there still version < 1.0 circulating?

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by AxandrasGaming** [comment]
Links from tutorials how to sync onedrive with linux ;-)

where can i get a newer version of it and why wAS i able to sync the firsttime?

**Comment by AxandrasGaming** [comment]
Sorry for my noobish handling with this, but i'm new with Linux / GitHub.
installing onedrive-d is ./setup.sh inst or?

installation seems to run smoothly, but when i ran onedrive-d / -prefs i got errors... when i try to remove it this meesages appears:

Removing Python 2 version of onedrive_d, if any.
Cannot uninstall requirement onedrive-d, not installed
Storing debug log for failure in /home/exarkun/.pip/pip.log

## pip.log: 

/usr/bin/pip run on Sun Feb  8 11:25:58 2015
Cannot uninstall requirement onedrive-d, not installed
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/uninstall.py", line 59, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1035, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 505, in uninstall
    raise UninstallationError("Cannot uninstall requirement %s, not installed" % (self.name,))
UninstallationError: Cannot uninstall requirement onedrive-d, not installed

**Comment by xybu** [comment]
So you don't have older version installed. Check out the manuall (un)installation guide in README.md in `future` branch.
