### ISSUE TITLE
Sync complete but no files only folders

### ISSUE THREAD

**Issue by jrock2004** [xybu/onedrive-d-old#111]
Running Ubuntu 14.04 and have installed the app. sync completes but all I see if folders. I am not seeing anything in /var/log for onedrive. Any thoughts? What do you need me to try to get you more info? Thanks

**Comment by jrock2004** [comment]
[2015-02-11T13:58:08-0500] syncer   INFO: syncing /home/jcostanzo/OneDrive/Camera Uploads/
[2015-02-11T13:58:15-0500] syncer   INFO: "/home/jcostanzo/OneDrive/Camera Uploads/2013-06-14 17.20.47.jpg is strictly newer. Upload it.
[2015-02-11T13:59:53-0500] syncer   DEBUG: Local file "/home/jcostanzo/OneDrive/Camera Uploads/2013-06-05 14.32.10 (alienware, older).jpg" does not exist remotely. Upload it.
[2015-02-11T13:59:53-0500] worker-1 DEBUG: I passed two locks.
[2015-02-11T13:59:53-0500] syncer   INFO: syncing /home/jcostanzo/OneDrive/Development/
[2015-02-11T13:59:53-0500] worker-0 DEBUG: I passed two locks.
[2015-02-11T13:59:53-0500] worker-1 DEBUG: I get a row from tasks table.
[2015-02-11T13:59:53-0500] worker-1 INFO: Uploading "/home/jcostanzo/OneDrive/Camera Uploads/2013-06-14 17.20.47.jpg".
[2015-02-11T13:59:54-0500] worker-0 DEBUG: I get a row from tasks table.
[2015-02-11T13:59:54-0500] worker-0 INFO: Downloading "/home/jcostanzo/OneDrive/Camera Uploads/2013-06-14 17.30.33.jpg".
[2015-02-11T13:59:54-0500] syncer   INFO: syncing /home/jcostanzo/OneDrive/Documents/
[2015-02-11T14:00:07-0500] syncer   INFO: syncing /home/jcostanzo/OneDrive/eBook/
[2015-02-11T14:00:09-0500] worker-0 DEBUG: I passed two locks.
Exception in thread worker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/jcostanzo/onedrive-d/onedrive_d/daemon.py", line 394, in run
    row = self.fetch_one_task()
  File "/home/jcostanzo/onedrive-d/onedrive_d/daemon.py", line 335, in fetch_one_task
    self.cursor.execute('SELECT \* FROM tasks WHERE priority=1 ORDER BY date_created ASC LIMIT 1')
sqlite3.OperationalError: database is locked

[2015-02-11T14:00:15-0500] syncer   INFO: syncing /home/jcostanzo/OneDrive/Invoices/
[2015-02-11T14:00:17-0500] syncer   INFO: syncing /home/jcostanzo/OneDrive/Mac Group/
[2015-02-11T14:00:18-0500] syncer   INFO: syncing /home/jcostanzo/OneDrive/Music/
[2015-02-11T14:00:19-0500] worker-1 DEBUG: I passed two locks.

**Comment by shekharmittal** [comment]
I am facing the same issue. Don't see any files on the browser.

**Comment by xybu** [comment]
The algorithm to traverse the repository is BFS. A dir is created if not exists as long as a task to sync its content is scheduled. And in dev version we do not handle exceptions (to expose as many problems as we can). As long as some issue happens the worker thread will die. So you will see dirs created but file sync halts some time. It is not "sync complete". I would suggest you check the program output and see what exception was thrown.

Sent from my Windows Phone
