### ISSUE TITLE
Error During Upload large file at the last block

### ISSUE THREAD

**Issue by tortoise4race** [xybu/onedrive-d-old#126]
OS: Wheezy 3.2.65-1+deb7u1
onedrive-d installed without requirements as workaround at post https://github.com/xybu/onedrive-d/issues/118
###### 

[2015-02-28 05:28:51,758] DEBUG: worker3: uploading block 7714897920 - 7715422207 (total: 7716807646 B)
[2015-02-28 05:28:53,187] DEBUG: worker3: uploading block 7715422208 - 7715946495 (total: 7716807646 B)
[2015-02-28 05:28:54,572] DEBUG: worker3: uploading block 7715946496 - 7716470783 (total: 7716807646 B)
[2015-02-28 05:28:55,951] DEBUG: worker3: uploading block 7716470784 - 7716807645 (total: 7716807646 B)
Exception in thread worker3:
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.2/dist-packages/onedrive_d-1.0.0dev-py3.2.egg/onedrive_d/od_worker_thread.py", line 454, in run
    self.upload_file(task)
  File "/usr/local/lib/python3.2/dist-packages/onedrive_d-1.0.0dev-py3.2.egg/onedrive_d/od_worker_thread.py", line 375, in upload_file
    block_size=self.config.params['BITS_BLOCK_SIZE'])
  File "/usr/local/lib/python3.2/dist-packages/onedrive_d-1.0.0dev-py3.2.egg/onedrive_d/od_onedrive_api.py", line 471, in bits_put
    res_id = response.headers['x-resource-id']
  File "/usr/local/lib/python3.2/dist-packages/requests-2.5.3-py3.2.egg/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-resource-id'

:

**Comment by xybu** [comment]
Looks like there is something special when downloading / uploading extremely large files. And the issues seem to point to the either close-session request or the last chunk.

Hopefully I can get to this issue next weekend. My coursework is killing me these days. Sorry 😥

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by xybu** [comment]
I checked. The access token expires after uploading that large file, making it an error closing the BITS session with the expired token. Will fix it shortly.
