### ISSUE TITLE
od_pref_gtk is not implemented yet

### ISSUE THREAD

**Issue by leoaloha** [xybu/onedrive-d-old#135]
When trying to run onedrive-pref --ui=gtk on Ubunti 14.10 w/Cinnimon get this error

~/onedrive-d$ onedrive-pref --ui=gtk
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-pref", line 9, in <module>
    load_entry_point('onedrive-d==1.1.0dev', 'console_scripts', 'onedrive-pref')()
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg/onedrive_d/od_pref.py", line 26, in main
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg/onedrive_d/od_pref_gtk.py", line 11, in **init**
NotImplementedError: od_pref_gtk is not implemented yet.

**Comment by lahtis** [comment]
Same is Ubuntu 14.04.

**Comment by chaaridev** [comment]
Same problem in  Ubuntu 14.04

**Comment by SierraSue** [comment]
Same in Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux.

**Comment by gerardbekking** [comment]
Same in Ubuntu Mate 14.04

**Comment by gnegno** [comment]
Same for me, linux Mint w/Cinnamon

**Comment by glpm64** [comment]
Same for me using ubuntu 14.10 / 15.04 beta.

**Comment by rodrigogirao** [comment]
Same in Linux mint 17 with cinnamon

**Comment by coyotte508** [comment]
Same in 15.04

**Comment by echyzowski** [comment]
Same issue 14.04.2 LTS - Gnome3
chance@chance-Aspire-ES1-512:~/onedrive-d$ onedrive-pref --ui=gtk
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-pref", line 9, in <module>
    load_entry_point('onedrive-d==1.1.0dev', 'console_scripts', 'onedrive-pref')()
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg/onedrive_d/od_pref.py", line 26, in main
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg/onedrive_d/od_pref_gtk.py", line 11, in **init**
NotImplementedError: od_pref_gtk is not implemented yet.

**Comment by et2010** [comment]
Same for me with Linux Mint 17 xfce. The CLI  onedrive-pref works fine.

Traceback (most recent call last):
  File "/usr/local/bin/onedrive-pref", line 9, in <module>
    load_entry_point('onedrive-d==1.1.0dev', 'console_scripts', 'onedrive-pref')()
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg/onedrive_d/od_pref.py", line 26, in main
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg/onedrive_d/od_pref_gtk.py", line 11, in **init**
NotImplementedError: od_pref_gtk is not implemented yet.

**Comment by jellespijker** [comment]
Same for me ubuntu 15.04

**Comment by vaikan** [comment]
Same here linux mint 17.1 cinammon 64-bit

**Comment by the-chris-strange** [comment]
same in Ubuntu 14.04

**Comment by hoppushoppard** [comment]
Same here:
Distributor ID: Ubuntu
Description:    Bodhi Linux
Release:    14.10
Codename:   utopic

But I think, it's because I don't have gtk installed ? :)

**Comment by tp0** [comment]
Developer, ping?

**Comment by echyzowski** [comment]
No responses 

Sent from Windows Mail

From: tp0
Sent: ‎Saturday‎, ‎June‎ ‎27‎, ‎2015 ‎11‎:‎19‎ ‎AM
To: xybu/onedrive-d
Cc: Ed Chyzowski

Developer, ping?

**Comment by ewann** [comment]
reviewing https://github.com/xybu/onedrive-d/blob/future/onedrive_d/od_pref_gtk.py it seems the gui/gtk version of the config tool simply isn't written yet, and the cli version should be used instead.

**Comment by z3ntu** [comment]
Same Ubuntu 15.04

**Comment by mrafaelbatista** [comment]
Same Ubuntu 15.10

**Comment by ghost** [comment]
It seems like the idea of using One Drive on Linux is just that a good idea, but the way things are now this is of no use to me.

**Comment by kabeza** [comment]
Same here. I'm on ElementaryOS Freya
NotImplementedError: od_pref_gtk is not implemented yet.

**Comment by romulogcerqueira** [comment]
Same Xubuntu 14.04.

**Comment by ahmadhsalim** [comment]
same Ubuntu 15.10

**Comment by alikhil** [comment]
Same Manjaro 16

**Comment by roberto0arruda** [comment]
The same here on Linux Mint 19 Cinnamon 64-bit!
* My suggestion is to just run the command:
```~$ onedrive-pref``` for configure command-line without GUI.
or [take a look here](https://github.com/xybu/onedrived-dev)

Example ```~$ onedrive-pref```:
```
user@MintOS:~$ onedrive-pref
Loading configuration ... OK
[2018-09-05 19:10:11,755] DEBUG: thread_mgr: started.
Setting up onedrive-d...
(STEP 1/4) Do you want to authorize sign in with your OneDrive account? [Y/n] Y

You will need to visit the OneDrive sign-in page in a browser, 
log in and authorize onedrive-d, and then copy and paste the 
callback URL, which should start with 
"https://login.live.com/oauth20_desktop.srf".

The callback URL is the URL where the sign-in page finally goes blank.

Please visit the sign-in URL in your browser:
- copy and visit the URL that appears on this line

Please paste the callback URL:
- copy to reply URL and paste here and press enter

[2018-09-05 19:11:36,705] DEBUG: MainThread: config saved.
onedrive-d has been successfully authorized.

(STEP 2/4) Do you want to specify path to local OneDrive repository? [Y/n] Y
Please enter the abs path to sync with your OneDrive (default: /home/user/OneDrive):
- specify your local directory here to sync
[2018-09-05 19:14:02,422] DEBUG: MainThread: config saved.
Path successfully set.

(STEP 3/4) Do you want to change the numeric settings? [Y/n] Y                                                       
* How many seconds to wait for before retrying a network failure (current: 10)?
* Files larger than what size (in MiB) will be uploaded blocks by blocks? (current: 4.0)?
* When a file is uploaded blocks by blocks, what is the block size (in KiB)? (current: 1024000.0)?
[2018-09-05 19:17:09,174] DEBUG: MainThread: config saved.

(STEP 4/4) Do you want to edit the ignore list file? [Y/n] Y
Calling your default editor...

You have exited from the text editor.
```

**Comment by LinkPhoenix** [comment]
Old post but @roberto0arruda Thank you !!!!

---

### for the callback URL:
1. Go to the URL that the script gives you
2. Connect
3. Accept the connection
4. Copy the URL of the blank page
