### ISSUE TITLE
pkg_resources.DistributionNotFound: psutil==2.1.1

### ISSUE THREAD

**Issue by elvisdx** [xybu/onedrive-d-old#136]
I'm receiving this messages

linux Mint Rebecca 17.1

onedrive-d start
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil==2.1.1

**Comment by xybu** [comment]
If you upgraded from a previous version in future branch, 

```
pip3 install daemonocle
```

**Comment by leoaloha** [comment]
Requirement already satisfied

L

**Comment by xybu** [comment]
Umm. I saw that daemonocle requires psutil==2.1.1, but the latest version of psutil is 2.2.1. Not sure if that's the cause. What does 

```
pip3 install psutil
```

say?

**Comment by ewholman** [comment]
I am running the same linux kernal as evisdx and I'm having the same issue. I noticed when installing package setup.pl, I got the following issue:

Installed /usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg
Processing dependencies for onedrive-d==1.1.0dev
Searching for psutil==2.1.1
Reading https://pypi.python.org/simple/psutil/
Best match: psutil 2.1.1
Downloading https://pypi.python.org/packages/source/p/psutil/psutil-2.1.1.tar.gz#md5=72a6b15d589fab11f6ca245b775bc3c6
Processing psutil-2.1.1.tar.gz
Writing /tmp/easy_install-g2j0spzh/psutil-2.1.1/setup.cfg
Running psutil-2.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-g2j0spzh/psutil-2.1.1/egg-dist-tmp-crjtvlkt
warning: no previously-included files matching '*' found under directory 'docs/_build'
psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

The "pip3 install psutil" returns:
Requirement already satisfied (use --upgrade to upgrade): psutil in /usr/lib/python3/dist-packages
Cleaning up...

When running "onedrive-d start" the following occurs:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (psutil 1.2.1 (/usr/lib/python3/dist-packages), Requirement.parse('psutil==2.1.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil==2.1.1

Also, "onedrive-pref" returns an issue with psutil:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (psutil 1.2.1 (/usr/lib/python3/dist-packages), Requirement.parse('psutil==2.1.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/onedrive-pref", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil==2.1.1

I hope this helps.

**Comment by xybu** [comment]
You need `python3-dev` package to compile `psutil`... That thing seems to be written in C and then bound with Python.

**Comment by ewholman** [comment]
Thanks. After installing python3-dev, it worked perfectly.
