### ISSUE TITLE
local_path and entry cannot both be NULL.

### ISSUE THREAD

**Issue by fokafoga** [xybu/onedrive-d-old#137]
I have downloaded last version. Well all worker threads with this exception, within a few minutes.

Exception in thread worker2:
Traceback (most recent call last):
  File "/usr/lib64/python3.3/threading.py", line 901, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.3/site-packages/onedrive_d-1.0.0dev-py3.3.egg/onedrive_d/od_worker_thread.py", line 448, in run
    self.sync_dir(task)
  File "/usr/lib/python3.3/site-packages/onedrive_d-1.0.0dev-py3.3.egg/onedrive_d/od_worker_thread.py", line 200, in sync_dir
    self.analyze_file_path(local_path, task['remote_id'], None, local_entries)
  File "/usr/lib/python3.3/site-packages/onedrive_d-1.0.0dev-py3.3.egg/onedrive_d/od_worker_thread.py", line 342, in analyze_file_path
    "analyze_file_path: local_path and entry cannot both be NULL.")
Exception: analyze_file_path: local_path and entry cannot both be NULL.

**Comment by fokafoga** [comment]
Sorry it was a 8 day old version.
I can't install the new version: https://github.com/xybu/onedrive-d/issues/138

**Comment by xybu** [comment]
I still have concern over the problem. If set up correctly there is no chance both of the two parameters mentioned are None. But there is no more detail for analysis. Kind of weird.

**Comment by fokafoga** [comment]
Hmm, the new version already don't do it. Thx.
