### ISSUE TITLE
Database locked?

### ISSUE THREAD

**Issue by eirinn1975** [xybu/onedrive-d-old#149]
Hello,
I'm running onedrive-d 1.0 on linux mint with x-face, but it's not synchronizing. I've tried with the debug mode and had the following:

[2015-04-07 16:50:01,443] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
[2015-04-07 16:50:01,845] DEBUG: thread_mgr: started.
[2015-04-07 16:50:02,001] DEBUG: MainThread: daemon started.
[2015-04-07 16:50:02,003] INFO: MainThread: token has expired. Try refreshing it.
[2015-04-07 16:50:03,045] INFO: MainThread: auto refreshed API token in face of auth error.
[2015-04-07 16:50:03,046] INFO: MainThread: successfully refreshed access token.
Exception in thread worker0:
Traceback (most recent call last):
  File "/usr/lib/python3.3/threading.py", line 637, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.3/dist-packages/onedrive_d-1.1.0dev-py3.3.egg/onedrive_d/od_worker_thread.py", line 426, in run
    self.entrymgr = od_sqlite.EntryManager()
  File "/usr/local/lib/python3.3/dist-packages/onedrive_d-1.1.0dev-py3.3.egg/onedrive_d/od_sqlite.py", line 150, in __init__
    """)
sqlite3.OperationalError: database is locked

I guess the last line says it all. How can I fix it?

**Comment by xybu** [comment]
Do you have other onedrive-d processes running? In a single process scenario, db lock cannot happen because each db access is guarded by a mutex lock.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by ewann** [comment]
@eirinn1975 did you manage to solve this situation?

**Comment by eirinn1975** [comment]
Yes! Sorry, I forgot to update this post. I just uninstalled and reinstalled everything, then everything was ok. I guess some dependancy installation went wrong.

Date: Wed, 22 Jul 2015 04:46:15 -0700

**Comment by ewann** [comment]
Thanks for the feedback.
