### ISSUE TITLE
Synced once but Folders Empty

### ISSUE THREAD

**Issue by KawaiMP6** [xybu/onedrive-d-old#158]
I finally managed to get onedrive-d to work under Mint with Kubuntu Desktop. But all of the synced Folders are empty. I moved Folders with the Web interface of Onedrive and the changes are not synced.

Here the Debugging Output:

[2015-05-04 20:01:19,970] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
[2015-05-04 20:01:20,116] DEBUG: thread_mgr: started.
[2015-05-04 20:01:20,184] DEBUG: MainThread: daemon started.
[2015-05-04 20:01:20,185] INFO: MainThread: token has expired. Try refreshing it.
[2015-05-04 20:01:21,287] INFO: MainThread: auto refreshed API token in face of auth error.
[2015-05-04 20:01:21,288] INFO: MainThread: successfully refreshed access token.
Exception in thread worker0:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg/onedrive_d/od_worker_thread.py", line 427, in run
    self.entrymgr = od_sqlite.EntryManager()
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg/onedrive_d/od_sqlite.py", line 151, in __init__
    self.cursor.execute('UPDATE entries SET visited=0')
sqlite3.OperationalError: attempt to write a readonly database

i am new to the whole linux world :-) 

any suggestions ?

P.S. sorry for my English and greetings from germany

**Comment by KawaiMP6** [comment]
Solved with sudo... embarrassing...

**Comment by xybu** [comment]
Your personal database, I.e., things in ~/.onedrive, shouldn't be owned by root. The script ./install.sh shouldn't run as root, either.

Sent from my Windows Phone
