### ISSUE TITLE
ImportError: cannot import name timezone

### ISSUE THREAD

**Issue by rizasif** [xybu/onedrive-d-old#176]
Hi I am using Ubuntu 15.04
I am stuck at the pref part and the same error pops up when I try to start onedrive-d

$ onedrive-pref
Traceback (most recent call last):
  File "/usr/bin/onedrive-pref", line 9, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-pref')()
  File "build/bdist.linux-x86_64/egg/onedrive_d/od_pref.py", line 28, in main
  File "build/bdist.linux-x86_64/egg/onedrive_d/od_pref_cli.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/onedrive_d/od_glob.py", line 13, in <module>
ImportError: cannot import name timezone

**Comment by xybu** [comment]
Were you using python2?

**Comment by rizasif** [comment]
Yea I was but python3 is giving error "No module named 'setuptools'"

**Comment by rizasif** [comment]
I got the it solved by installing through
sudo ./install.sh
