### ISSUE TITLE
Uploading folder having git repository (and python code)

### ISSUE THREAD

**Issue by Dr-Xperience** [xybu/onedrive-d-old#177]
I am trying to upload a folder having git repository (.git folder) and having python code in it. I am facing following exception.

xception in thread worker1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/site-packages/onedrive_d-1.1.0.dev0-py3.4.egg/onedrive_d/od_worker_thread.py", line 446, in run
    self.upload_file(task)
  File "/usr/lib/python3.4/site-packages/onedrive_d-1.1.0.dev0-py3.4.egg/onedrive_d/od_worker_thread.py", line 367, in upload_file
    block_size=self.config.params['BITS_BLOCK_SIZE'])
  File "/usr/lib/python3.4/site-packages/onedrive_d-1.1.0.dev0-py3.4.egg/onedrive_d/od_onedrive_api.py", line 517, in bits_put
    return self.get_property('file.' + res_id[:res_id.index('!')] + '.' + res_id)
  File "/usr/lib/python3.4/site-packages/onedrive_d-1.1.0.dev0-py3.4.egg/onedrive_d/od_onedrive_api.py", line 247, in get_property
    return self.parse_response(r, OneDriveAPIException)
  File "/usr/lib/python3.4/site-packages/onedrive_d-1.1.0.dev0-py3.4.egg/onedrive_d/od_onedrive_api.py", line 115, in parse_response
    raise error(ret)
onedrive_d.od_onedrive_api.OneDriveAPIException: The URL contains the path 'file.351814d0da5818c.351814d0da5818c!4050', which isn't supported. (request_url_invalid)

Any sort of help is appreciated.

**Comment by xybu** [comment]
The short answer is, OneDrive server doesn't want that file and refuses the upload request.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by Dr-Xperience** [comment]
So this means one drive doesn't work well with .git folder. Thanks, I will try zipping them up.

**Comment by Dr-Xperience** [comment]
Sorry just saw this issue https://github.com/xybu/onedrive-d-old/issues/160. Can you (@xybu) confirm this issue is similar to mine. And is there a fix to it in your new version. I mean I desperately need to use onedrive for some professional reason.
