### ISSUE TITLE
Unable to install (ubuntu 14.04)

### ISSUE THREAD

**Issue by bjs-pdx** [xybu/onedrive-d-old#183]
While trying to install this version of onedrive-d I get the following error messages:
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
  File "/usr/local/lib/python3.4/dist-packages/setuptools/**init**.py", line 12, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python3.4/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'
Any idea as to what may be wrong?

**Comment by bjs-pdx** [comment]
Here is the complete output from my attempt to run install.sh:

~/onedrive-d-old$ sudo ./install.sh
**python3 installed...OK**
Reading package lists... Done
Building dependency tree  
Reading state information... Done
**python3-dev is already the newest version.**
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
**pip3 installed...OK**
**inotifywait installed...OK**
Reading package lists... Done
Building dependency tree  
Reading state information... Done
**inotify-tools is already the newest version.**
**python3-gi is already the newest version.**
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
  File "/usr/local/lib/python3.4/dist-packages/setuptools/**init**.py", line 12, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python3.4/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'

Does anyone have any idea what is wrong?  I have found **onedrive-d** and **onedrive-pref** in /usr/local/bin but I get different errors when I try to run either of them.

**Comment by ajeckmans** [comment]
You should take a look at this: https://github.com/xybu/onedrive-d-old/issues/174

**Comment by bjs-pdx** [comment]
Thank you so much.  That was the problem.
