### ISSUE TITLE
exit code 127

### ISSUE THREAD

**Issue by zt-luo** [xybu/onedrive-d-old#198]
Arch ~]$ onedrive-d start
Loading configuration ... OK
[2016-02-24 09:44:32,451] DEBUG: MainThread: running in daemon node.
Starting onedrive-d ... FAILED
ERROR: Child exited immediately with non-zero exit code 127

**Comment by xybu** [comment]
Try debug mode and see what's wrong.

**Comment by junop97** [comment]
Loading configuration ... OK
[2016-04-10 17:19:20,226] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
[2016-04-10 17:19:20,317] DEBUG: thread_mgr: started.
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python3.5/site-packages/click-2.5-py3.5.egg/click/core.py", line 488, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python3.5/site-packages/click-2.5-py3.5.egg/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click-2.5-py3.5.egg/click/core.py", line 758, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python3.5/site-packages/click-2.5-py3.5.egg/click/core.py", line 767, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python3.5/site-packages/click-2.5-py3.5.egg/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click-2.5-py3.5.egg/click/core.py", line 325, in invoke
    return callback(_args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/daemonocle-0.8-py3.5.egg/daemonocle/cli.py", line 56, in subcommand
  File "/usr/local/lib/python3.5/site-packages/daemonocle-0.8-py3.5.egg/daemonocle/daemon.py", line 573, in do_action
  File "/usr/local/lib/python3.5/site-packages/daemonocle-0.8-py3.5.egg/daemonocle/daemon.py", line 444, in start
  File "/usr/local/lib/python3.5/site-packages/daemonocle-0.8-py3.5.egg/daemonocle/daemon.py", line 367, in _run
  File "/usr/local/lib/python3.5/site-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_main.py", line 28, in main
  File "/usr/local/lib/python3.5/site-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_mon_cli.py", line 12, in <module>
  File "/usr/local/lib/python3.5/site-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_sqlite.py", line 9, in <module>
  File "/usr/local/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
All children are gone. Parent is exiting...

**Comment by Royloco** [comment]
make a .onedrive-d folder
run $onedrive-pref

**Comment by mdoprog** [comment]
I'm having the same error code on Linux Mint 19.1 Tessa, base: Ubuntu 18.04 bionic. Follow the debug information:

onedrive-d$ onedrive-d start --debug
Loading configuration ... OK
[2019-06-11 20:54:10,204] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
[2019-06-11 20:54:10,299] DEBUG: thread_mgr: started.
[2019-06-11 20:54:10,343] DEBUG: MainThread: daemon started.
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 11, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/cli.py", line 57, in subcommand
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 608, in do_action
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 477, in start
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 399, in _run
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_main.py", line 36, in main
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_mon_cli.py", line 112, in start
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_mon_cli.py", line 48, in load_token
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_onedrive_api.py", line 247, in get_propertyf 
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_onedrive_api.py", line 115, in parse_response
onedrive_d.od_onedrive_api.OneDriveAPIException: This API is no longer supported. Please see https://aka.ms/livesdkmigration for information about migrating your application to Microsoft Graph. (api_deprecated)
[2019-06-11 20:54:11,195] DEBUG: MainThread: cleaning up.
All children are gone. Parent is exiting...

I'll be thankful if anyone can help me.

**Comment by paatric** [comment]
I tried with creating a ondedrive-d folder but it did not work. Still same answer. I use Mint 19.1

**Comment by looneyboymint** [comment]
I have the same kind of issue, is it because of two way authentication on my microsoft account?

debug file:
 advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[2019-12-06 11:36:22,356] DEBUG: MainThread: config saved.
onedrive-d has been successfully authorized.

(STEP 2/4) Do you want to specify path to local OneDrive repository? [Y/n] y
Please enter the abs path to sync with your OneDrive (default: /home/ronald/OneDrive): /home/ronald/onedrive
[2019-12-06 11:39:45,901] DEBUG: MainThread: config saved.
Path successfully set.

(STEP 3/4) Do you want to change the numeric settings? [Y/n] n
Skipped.

(STEP 4/4) Do you want to edit the ignore list file? [Y/n] n
Skipped. You can manually edit "/home/ronald/.onedrive/ignore_v2.ini" at your convenience.

All steps are finished.
[2019-12-06 11:39:56,765] DEBUG: Dummy-2: config saved.
ronald@ronald-HP-ProBook-4520s ~/onedrive-d $ onedrive-d start
Loading configuration ... OK
[2019-12-06 11:40:20,081] DEBUG: MainThread: running in daemon node.
Starting onedrive-d ... FAILED
ERROR: Child exited immediately with exit code 127
ronald@ronald-HP-ProBook-4520s ~/onedrive-d $ onedrive-d start --debug
Loading configuration ... OK
[2019-12-06 13:07:59,807] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
[2019-12-06 13:07:59,934] DEBUG: thread_mgr: started.
[2019-12-06 13:07:59,986] DEBUG: MainThread: daemon started.
[2019-12-06 13:07:59,987] INFO: MainThread: token has expired. Try refreshing it.
[2019-12-06 13:08:00,755] INFO: MainThread: auto refreshed API token in face of auth error.
[2019-12-06 13:08:00,755] INFO: MainThread: successfully refreshed access token.
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python3.5/dist-packages/Click-7.0-py3.5.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Click-7.0-py3.5.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/Click-7.0-py3.5.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/Click-7.0-py3.5.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/Click-7.0-py3.5.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/cli.py", line 57, in subcommand
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/core.py", line 608, in do_action
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/core.py", line 477, in start
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/core.py", line 399, in _run
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_main.py", line 36, in main
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_mon_cli.py", line 112, in start
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_mon_cli.py", line 48, in load_token
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_onedrive_api.py", line 247, in get_property
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_onedrive_api.py", line 115, in parse_response
onedrive_d.od_onedrive_api.OneDriveAPIException: This API is no longer supported. Please see https://aka.ms/livesdkmigration for information about migrating your application to Microsoft Graph. (api_deprecated)
[2019-12-06 13:08:00,907] DEBUG: Dummy-2: cleaning up.
[2019-12-06 13:08:00,907] DEBUG: Dummy-2: config saved.
All children are gone. Parent is exiting...
ronald@ronald-HP-ProBook-4520s ~/onedrive-d $ 

hope anyone recognizes this issue and have a fix
