### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by romulogcerqueira** [xybu/onedrive-d-old#205]
I ran the command `sudo python3 setup.py install` and I got this error:

<pre>
Installed /usr/local/lib/python3.4/dist-packages/onedrive_d-1.1.0dev-py3.4.egg
Processing dependencies for onedrive-d==1.1.0dev
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2273, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map
</pre>

I have used the Xubuntu 14.04.

**Comment by romulogcerqueira** [comment]
I solved this error by executing `sudo python3 setup.py clean` before to install.

**Comment by Steamless** [comment]
Hi! 
When I run `sudo python3 setup.py install` or `sudo python3 setup.py clean` I get this error:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

I have Mint.

Any idea about this?

**Comment by ghost** [comment]
Hi there,

I have the same issue as you Steamless. Maybe you can share your solution if you find it or hope anyone could help us out :)
I'm using Mint too.

Thanks

**Comment by ghost** [comment]
Found it.

Install the setup tools, simple as that.

sudo apt-get install python3-setuptools
and
sudo python3 setup.py install

**Comment by samirm** [comment]
@SVersluis your solution worked for me. Thank you!
