### ISSUE TITLE
cant start onedrive

### ISSUE THREAD

**Issue by vasilimertzani** [xybu/onedrive-d-old#208]
i m trying to install it in two pcs and getting the same error.
Loading configuration ... OK
[2016-07-29 22:22:27,280] DEBUG: MainThread: running in daemon node.
Starting onedrive-d ... FAILED
ERROR: Child exited immediately with exit code 1

the pc running
linux mint 18 sarah 64bit.
any further assisant would be helpfull.

**Comment by brendjuan** [comment]
run "onedrive-d start --debug" and post what outputs.
also ensure that you've already run "onedrive-pref" and followed it through

**Comment by vakili73** [comment]
i m trying too.
Loading configuration ... OK
[2016-11-21 00:10:15,528] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
[2016-11-21 00:10:15,615] DEBUG: thread_mgr: started.
[2016-11-21 00:10:15,649] DEBUG: MainThread: daemon started.
[2016-11-21 00:10:15,650] CRITICAL: MainThread: no user is associated with onedrive-d.
[2016-11-21 00:10:15,650] DEBUG: Dummy-2: cleaning up.
All children are gone. Parent is exiting...

**Comment by brendjuan** [comment]
"no user is associated with onedrive-d" seems to imply that "onedrive-pref" was never run properly or all the way through. Is this just on one machine? What distro are you running on?

**Comment by cadone02** [comment]
Hi brendjuan,
i have a some problem with onedrive-d. i had not started onedrive-d , please help to fix below error:
[root@localhost ~]# onedrive-d start
Loading configuration ... OK
[2017-04-14 00:23:14,623] DEBUG: MainThread: running in daemon node.
Starting onedrive-d ... FAILED
ERROR: Child exited immediately with exit code 1
[root@localhost ~]# onedrive-d start --debug
Loading configuration ... OK
[2017-04-14 00:23:34,149] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 11, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/cli.py", line 57, in subcommand
  File "/usr/local/lib/python3.6/site-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 608, in do_action
  File "/usr/local/lib/python3.6/site-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 470, in start
  File "/usr/local/lib/python3.6/site-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 120, in _write_pidfile
OSError: [Errno 28] No space left on device: '/root/.onedrive/onedrive.pid'
All children are gone. Parent is exiting...

**Comment by brendjuan** [comment]
Based on the second to last line of the output.  It seems you dont have space on your partition*. if you run "df -h" and check the output. look on the right most column and find, prolly "/root" or "/" and check the "use%" column to see how much space you have.

**Comment by renewalsch** [comment]
Hi brendjuan, do I understand correctly that onedrive-d checks the total space used in OneDrive and compares it to the free space on the harddrive? So onedrive-d tries to sync all content in the cloud even if most of my cloud folders are marked as "do not sync" in the cloud?

**Comment by thiago-goncalves-souza** [comment]
Hi @brendjuan ,

I'm having a similar problem. I have configured 'onedrive-pref' and authorized my account. However, I got the same error. I used --debug and received the following:

Loading configuration ... OK
[2019-01-16 09:57:08,819] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
[2019-01-16 09:57:08,887] DEBUG: thread_mgr: started.
[2019-01-16 09:57:08,916] DEBUG: MainThread: daemon started.
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 11, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/cli.py", line 57, in subcommand
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 608, in do_action
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 477, in start
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 399, in _run
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_main.py", line 36, in main
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_mon_cli.py", line 112, in start
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_mon_cli.py", line 48, in load_token
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_onedrive_api.py", line 247, in get_property
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_onedrive_api.py", line 115, in parse_response
onedrive_d.od_onedrive_api.OneDriveAPIException: This API is no longer supported. Please see https://aka.ms/livesdkmigration for information about migrating your application to Microsoft Graph. (api_deprecated)
[2019-01-16 09:57:09,673] DEBUG: MainThread: cleaning up.
All children are gone. Parent is exiting...

Thank you in advance.

**Comment by avitevet** [comment]
@thiagotoyoyo I am also getting an api_deprecated error.  I installed and ran the onedrive-d service for the first time today.  I wonder if MS has recently changed their API?

**Comment by brendjuan** [comment]
@avitevet @thiagotoyoyo Yeah, I think MS changed the onedrive API. Microsoft Graph seems to be what they use now (instead of Live SDK). I would suggest taking a look at https://github.com/xybu/onedrived-dev , instead of onedrive-d-old.

**Comment by avitevet** [comment]
Alright, thanks for the pointer.

**Comment by thiago-goncalves-souza** [comment]
Thank you. I'll try the onedrive-dev

**Comment by thiago-goncalves-souza** [comment]
I could not install it. This there are some error messages:

running test
Searching for requests-mock
Best match: requests-mock 1.5.2
Processing requests_mock-1.5.2-py3.6.egg

Using /home/ecofun/onedrived-dev/.eggs/requests_mock-1.5.2-py3.6.egg
running egg_info
writing onedrived.egg-info/PKG-INFO
writing dependency_links to onedrived.egg-info/dependency_links.txt
writing entry points to onedrived.egg-info/entry_points.txt
writing requirements to onedrived.egg-info/requires.txt
writing top-level names to onedrived.egg-info/top_level.txt
reading manifest file 'onedrived.egg-info/SOURCES.txt'
writing manifest file 'onedrived.egg-info/SOURCES.txt'
running build_ext
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/home/ecofun/.config/onedrived/onedrived_config_v2.json'. Use default.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/home/ecofun/.config/onedrived/onedrived_config_v2.json'. Use default.
test_execution (tests.test_webhook_worker.TestWebhookWorker) ... ERROR:root:Unknown subscription ID "233".
ok
test_get_os_stat (tests.test_tasks.TestMergeDirTask) ... ok
test_list_local_names (tests.test_tasks.TestMergeDirTask) ... ok
test_remote_dir_matches_record (tests.test_tasks.TestMergeDirTask) ... ok
test_rename_with_suffix (tests.test_tasks.TestMergeDirTask) ... ok
test_rename_with_suffix_and_count (tests.test_tasks.TestMergeDirTask) ... ok
test_handle (tests.test_tasks.TestStartRepositoryTask) ... ok
test_task_base (tests.test_tasks.TestTaskBase) ... ok
test_handle_create (tests.test_tasks.TestUpdateSubscriptionTask) ... ok
test_handle_update (tests.test_tasks.TestUpdateSubscriptionTask) ... ok
test_add_get_items (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_delete_file (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_delete_folder (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_get_immediate_children (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_get_immediate_children_of_root (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_move_item_down (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_move_item_up (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_properties (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_properties (tests.test_models.TestAccountProfile) ... ok
test_to_string (tests.test_models.TestAccountProfile) ... ok
test_use (tests.test_models.TestBidict) ... ok
test_properties (tests.test_models.TestDriveConfig) ... ok
test_add_rules (tests.test_models.TestPathFilter) ... ok
test_auto_correction (tests.test_models.TestPathFilter) ... ok
test_hardcoded_cases (tests.test_models.TestPathFilter) ... ok
test_ignore_general (tests.test_models.TestPathFilter) ... ok
test_ignore_in_root (tests.test_models.TestPathFilter) ... ok
test_ignore_path (tests.test_models.TestPathFilter) ... ok
test_negations (tests.test_models.TestPathFilter) ... ok
test_special_patterns (tests.test_models.TestPathFilter) ... ok
test_pretty_print_bytes (tests.test_models.TestPrettyApi) ... ok
test_properties (tests.test_models.TestWebhookNotification) ... ok
test_properties_missing_context (tests.test_models.TestWebhookNotification) ... ok
test_properties_missing_tenant_id (tests.test_models.TestWebhookNotification) ... ok
test_datetime_to_str (tests.test_dateutils.TestDateUtils) ... ok
test_datetime_to_timestamp_explicit_utc (tests.test_dateutils.TestDateUtils) ... ok
test_datetime_to_timestamp_implicit_utc (tests.test_dateutils.TestDateUtils) ... ok
test_datetime_to_timestamp_non_utc (tests.test_dateutils.TestDateUtils) ... ok
test_diff_timestamps (tests.test_dateutils.TestDateUtils) ... ok
test_str_to_datetime (tests.test_dateutils.TestDateUtils) ... ok
test_init_and_shutdown_task_workers (tests.test_main_cli.TestMainCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp_uoi7psc/onedrived/onedrived_config_v2.json'. Use default.
ok
test_expires_in (tests.test_api_session.OneDriveAPISession) ... ok
test_save_and_load (tests.test_api_session.OneDriveAPISession) ... ERROR
test_hash (tests.test_hashutils.TestHashUtils) ... ok
test_hash_match (tests.test_hashutils.TestHashUtils) ... ok
test_get_auth_url (tests.test_auth.TestOneDriveAuthenticator) ... ok
test_get_proxies (tests.test_auth.TestOneDriveAuthenticator) ... ok
test_lifecycle (tests.test_threads.TestTaskWorkerThread) ... ok
test_config_schema (tests.test_dict_guard.TestConfigSchema) ... ok
test_set_arbitrary_key (tests.test_dict_guard.TestDictGuard) ... ok
test_set_int (tests.test_dict_guard.TestDictGuard) ... ok
test_set_int_above_max (tests.test_dict_guard.TestDictGuard) ... ok
test_set_int_below_min (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_create_file_if_missing (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_empty (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_out_of_choice (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_to_int (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_with_non_file_path (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_with_permission_denied (tests.test_dict_guard.TestDictGuard) ... ok
test_str_not_starts_with (tests.test_dict_guard.TestDictGuard) ... ok
test_str_with_permission_allowed (tests.test_dict_guard.TestDictGuard) ... ok
test_add_drive (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpbnl83_yn/onedrived/onedrived_config_v2.json'. Use default.
Reading drives information from OneDrive server...

All available Drives of authorized accounts:

#    Account Email    Drive ID    Type    Quota    Status
---  ---------------  ----------  ------  -------  --------

Did not find existing account with email address "xybu92@live.com".
/usr/lib/python3.6/tempfile.py:939: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpus619zrt'>
  _warnings.warn(warn_message, ResourceWarning)
ok
test_authenticate_account_with_code (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmps3ae3tfo/onedrived/onedrived_config_v2.json'. Use default.
NOTE: To better manage your OneDrive accounts, onedrived needs permission to access your account info (e.g., email address to distinguish different accounts) and read/write your OneDrive files.

Successfully authorized onedrived.
Successfully added account for Xiangyu Bu (foo@bar.com)!

All OneDrive accounts associated with user "ecofun":

  #  Account ID    Owner Name    Email Address
---  ------------  ------------  ---------------
  0  713d61        Xiangyu Bu    foo@bar.com
ok
test_authenticate_account_with_url (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpkwud6v1b/onedrived/onedrived_config_v2.json'. Use default.
NOTE: To better manage your OneDrive accounts, onedrived needs permission to access your account info (e.g., email address to distinguish different accounts) and read/write your OneDrive files.

Paste this URL into your browser to sign in and authorize onedrived:

https://login.live.com/oauth20_authorize.srf?client_id=000000004010C916&response_type=code&redirect_uri=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf&scope=wl.signin+wl.emails+wl.offline_access+onedrive.readwrite

The authentication web page will finish with a blank page whose URL starts with "https://login.live.com/oauth20_desktop.srf". Paste this URL after the prompt.
Successfully authorized onedrived.
/usr/lib/python3.6/json/encoder.py:353: ResourceWarning: unclosed <socket.socket fd=27, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  items = sorted(dct.items(), key=lambda kv: kv[0])
/usr/lib/python3.6/json/encoder.py:353: ResourceWarning: unclosed <socket.socket fd=28, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  items = sorted(dct.items(), key=lambda kv: kv[0])
/usr/lib/python3.6/json/encoder.py:353: ResourceWarning: unclosed <socket.socket fd=29, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  items = sorted(dct.items(), key=lambda kv: kv[0])
Successfully added account for Xiangyu Bu (foo@bar.com)!

All OneDrive accounts associated with user "ecofun":

  #  Account ID    Owner Name    Email Address
---  ------------  ------------  ---------------
  0  713d61        Xiangyu Bu    foo@bar.com
ok
test_config_print (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpsl2sqyun/onedrived/onedrived_config_v2.json'. Use default.
# Path to log file. Empty string means writing to stdout.
logfile_path = 

# Total number of worker threads.
num_workers = 2

# Interval, in seconds, between two actions of scanning the entire repository.
scan_interval_sec = 21600

# Amount of time, in seconds, to sleep before main starts working.
start_delay_sec = 0

# Wait for this period of time before acting (usually a merge action) after a webhook notification is received. During this period duplicate notifications can be merged.
webhook_action_delay_sec = 120

# Hostname in webhook URL. Used in "direct" webhook and must resolve to local host. Leave blank to use public IP of the machine.
webhook_host = 

# Port number for webhook. Default: 0 (let OS allocate a free port).
webhook_port = 0

# Renew webhook after this amount of time, in seconds. Ideal value should be slightly larger than the lifespan of onedrived process.
webhook_renew_interval_sec = 7200

# Type of webhook. Use "direct" only if your machine can be reached from public network.
webhook_type = ngrok

ok
test_config_set_invalid_str (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpu3saqmqo/onedrived/onedrived_config_v2.json'. Use default.
Invalid value "whatever" for "webhook_type": must be a choice from direct, ngrok.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpu3saqmqo/onedrived/onedrived_config_v2.json'. Use default.
Invalid value for "logfile_path": path "/" is not a file.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpu3saqmqo/onedrived/onedrived_config_v2.json'. Use default.
Invalid value for "webhook_port": no more than 65535; got 70000.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpu3saqmqo/onedrived/onedrived_config_v2.json'. Use default.
Invalid value for "num_workers": no less than 1; got 0.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpu3saqmqo/onedrived/onedrived_config_v2.json'. Use default.
ok
test_config_set_key_typo (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpnc0q9zll/onedrived/onedrived_config_v2.json'. Use default.
Usage: setup.py [OPTIONS] [logfile_path|num_workers|scan_interval_sec|start_de
                lay_sec|webhook_action_delay_sec|webhook_host|webhook_port|web
                hook_renew_interval_sec|webhook_type] VALUE
Try "setup.py --help" for help.

Error: Invalid value for "[logfile_path|num_workers|scan_interval_sec|start_delay_sec|webhook_action_delay_sec|webhook_host|webhook_port|webhook_renew_interval_sec|webhook_type]": invalid choice: webhook_typo. (choose from logfile_path, num_workers, scan_interval_sec, start_delay_sec, webhook_action_delay_sec, webhook_host, webhook_port, webhook_renew_interval_sec, webhook_type)
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpnc0q9zll/onedrived/onedrived_config_v2.json'. Use default.
ok
test_config_set_valid (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp75qjuhqj/onedrived/onedrived_config_v2.json'. Use default.
config.webhook_type = direct
config.webhook_port = 0
config.logfile_path = /tmp/tmp75qjuhqj/test.log
ok
test_del_drive (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp2_s_mezt/onedrived/onedrived_config_v2.json'. Use default.
Reading drives information from OneDrive server...

Error: a bytes-like object is required, not 'list'.
/usr/lib/python3.6/tempfile.py:939: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpwpov7pob'>
  _warnings.warn(warn_message, ResourceWarning)
Drives that have been set up:
 No Drive has been setup with onedrived.

ok
test_list_account (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpyyuhelxt/onedrived/onedrived_config_v2.json'. Use default.
All OneDrive accounts associated with user "ecofun":

  #  Account ID    Owner Name    Email Address
---  ------------  ------------  ---------------
  0  713d61        Xiangyu Bu    foo@bar.com
ok
test_list_drives (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpgs0xc6hc/onedrived/onedrived_config_v2.json'. Use default.
Reading drives information from OneDrive server...

/home/ecofun/.local/lib/python3.6/site-packages/jeepney/low_level.py:251: ResourceWarning: unclosed <socket.socket fd=27, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  valtype = parse_signature(list(sig))
Error: a bytes-like object is required, not 'list'.
ok
test_quota_short_str (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmprh0_gvl2/onedrived/onedrived_config_v2.json'. Use default.
ok
test_get_filename_with_incremented_count (tests.test_stringutils.TestStringUtils) ... ok
test_get_login_username (tests.test_context.TestUserContext) ... ok
test_recognize_event_patterns (tests.test_watcher.TestLocalRepositoryWatcher) ... ok
test_add_pop (tests.test_task_pool.TestTaskPool) ... ok
test_has_pending_task (tests.test_task_pool.TestTaskPool) ... ok
test_occupy_failure (tests.test_task_pool.TestTaskPool) ... ok
test_occupy_release_path (tests.test_task_pool.TestTaskPool) ... ok
test_remove_children_tasks (tests.test_task_pool.TestTaskPool) ... ok
test_get_item_created_datetime (tests.test_api_helper.TestApiHelper) ... ok
test_get_item_modified_datetime_modifiable (tests.test_api_helper.TestApiHelper) ... ok
test_get_item_modified_datetime_unmodifiable (tests.test_api_helper.TestApiHelper) ... ok
test_item_request_call_on_connection_error (tests.test_api_helper.TestApiHelper) ... ERROR:root:Encountered connection error: . Retry in 60 sec.
ok
test_item_request_call_on_unauthorized_error (tests.test_api_helper.TestApiHelper) ... ERROR:root:Encountered API Error: unauthenticated - dummy.
ok

======================================================================
ERROR: test_save_and_load (tests.test_api_session.OneDriveAPISession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ecofun/onedrived-dev/tests/test_api_session.py", line 22, in test_save_and_load
    session = od_api_session.OneDriveAPISession.load_session(**keydict)
  File "/home/ecofun/onedrived-dev/onedrived/od_api_session.py", line 40, in load_session
    saved_data = keyring.get_password(OneDriveAPISession.KEYRING_SERVICE_NAME, load_session_kwargs[keyarg])
  File "/home/ecofun/.local/lib/python3.6/site-packages/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/ecofun/.local/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 72, in get_password
    return item.get_secret().decode('utf-8')
  File "/home/ecofun/.local/lib/python3.6/site-packages/secretstorage/item.py", line 106, in get_secret
    padded_secret = decryptor.update(encrypted_secret) + decryptor.finalize()
  File "/home/ecofun/.local/lib/python3.6/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/home/ecofun/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 124, in update
    n = self.update_into(data, buf)
  File "/home/ecofun/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 140, in update_into
    self._backend._ffi.from_buffer(data), len(data)
TypeError: a bytes-like object is required, not 'list'

----------------------------------------------------------------------
Ran 86 tests in 5.233s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=86 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=86 errors=1 failures=0>

**Comment by ghost** [comment]
I also got a problem when starting onedrived :
stephan@Stephan-Laptop:~$ sudo onedrived start --debug
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.secrets': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/onedrived", line 6, in <module>
    from onedrived.od_main import main
  File "/usr/local/lib/python3.6/dist-packages/onedrived/od_main.py", line 20, in <module>
    from .od_auth import get_authenticator_and_drives
  File "/usr/local/lib/python3.6/dist-packages/onedrived/od_auth.py", line 15, in <module>
    from . import od_api_session
  File "/usr/local/lib/python3.6/dist-packages/onedrived/od_api_session.py", line 6, in <module>
    import keyring
  File "/usr/lib/python3/dist-packages/keyring/__init__.py", line 3, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 153, in <module>
    init_backend()
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 66, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/lib/python3/dist-packages/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/keyring/backend.py", line 196, in get_all_keyring
    exceptions=TypeError))
  File "/usr/lib/python3/dist-packages/keyring/util/__init__.py", line 31, in suppress_exceptions
    for callable in callables:
  File "/usr/lib/python3/dist-packages/keyring/backend.py", line 188, in is_class_viable
    keyring_cls.priority
  File "/usr/lib/python3/dist-packages/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python3/dist-packages/keyring/backends/SecretService.py", line 38, in priority
    list(secretstorage.get_all_collections(bus))
  File "/usr/lib/python3/dist-packages/secretstorage/collection.py", line 144, in get_all_collections
    service_obj = bus_get_object(bus, SS_PATH)
  File "/usr/lib/python3/dist-packages/secretstorage/util.py", line 55, in bus_get_object
    return bus.get_object(name, object_path, introspect=False)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
