### ISSUE TITLE
Error when running sync OneDrive

### ISSUE THREAD

**Issue by linuxsoid** [xybu/onedrive-d-old#214]
In General, working with Ubuntu, Ubuntu LTS 16.04.1, installation of OneDrive, when you try to run the first sync using the commands:

onedrive-d start
onedrive-d

I see the error:
`Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_main.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/cli.py", line 8, in <module>
AttributeError: module 'click' has no attribute 'MultiCommand'`

Help to decide as I don't understand, what exactly is the problem, I read on a similar problem on http://askubuntu.com/questions/613512/how-to-get-removed-a-broken-package-in-this-case-click but it's kind of not the same thing.

**Comment by CorruptMilkshake** [comment]
Can't say I know what your issue is but it's working perfectly for me on Ubuntu 16.04.1. I assume you've tried the usual removing, re-downloading and reinstalling?

**Comment by linuxsoid** [comment]
I've switched to using Ubuntu 16.10 Yakkety Yak, installed and same problem again.
`
root@lunuxsoid:/# onedrive-d start
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 11, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2249, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_main.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/cli.py", line 8, in <module>
AttributeError: module 'click' has no attribute 'MultiCommand'
`
Don't know what to do, errors and again errors, how to fix them, no idea.

**Comment by hopicker** [comment]
I am getting the same behavior. I uninstalled Click and re-install it, reboot but no improvements.

~$ onedrive-d start
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_main.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/cli.py", line 8, in <module>
AttributeError: module 'click' has no attribute 'MultiCommand'

**Comment by xybu** [comment]
Seems click package used by the daemonicle package has some API changes and caused problem to daemonicle and thus the CLI.

Sincerely,
Xiangyu Bu

Sent from Outlook

On Sun, Oct 9, 2016 at 3:46 AM -0400, "luk4196" notifications@github.com wrote:

I've switched to using Ubuntu 16.10 Yakkety Yak, installed and same problem again.
`
root@lunuxsoid:/# onedrive-d start
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 11, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2249, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_main.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/cli.py", line 8, in <module>
AttributeError: module 'click' has no attribute 'MultiCommand'
`
Don't know what to do, errors and again errors, how to fix them, no idea.

##

**Comment by xybu** [comment]
Can you post the version of your click / daemonicle packages?

Sincerely,
Xiangyu Bu

Sent from Outlook

On Sun, Oct 9, 2016 at 1:36 PM -0400, "Xiangyu Bu" xybu92@live.com wrote:

Seems click package used by the daemonicle package has some API changes and caused problem to daemonicle and thus the CLI.

Sincerely,
Xiangyu Bu

Sent from Outlook

On Sun, Oct 9, 2016 at 3:46 AM -0400, "luk4196" notifications@github.com wrote:

I've switched to using Ubuntu 16.10 Yakkety Yak, installed and same problem again.
`
root@lunuxsoid:/# onedrive-d start
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 11, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2249, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_main.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/cli.py", line 8, in <module>
AttributeError: module 'click' has no attribute 'MultiCommand'
`
Don't know what to do, errors and again errors, how to fix them, no idea.

##

**Comment by linuxsoid** [comment]
**Xubu**, Version package click if you about it I - "0.4.45.1+16.10.20160916-0ubuntu1"

**Comment by hopicker** [comment]
Hi,

Here is my Click version : click is already the newest version 
(0.4.43+16.04.20160203-0ubuntu2)

Best regards

Hopicker

**Comment by linuxsoid** [comment]
**Xubu,** Hello. Aren't there any ideas to fix? Because the problem is not only in me.

**Comment by heliobentes** [comment]
@luk4196, I was facing this same issue.

Try:

`sudo pip3 install click --upgrade`

**Comment by hopicker** [comment]
Unfortunately, same punishment :-(

Onedrive-d$ onedrive-d start
Traceback (most recent call last):
   File "/usr/local/bin/onedrive-d", line 9, in <module>
     load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 
'onedrive-d')()
   File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 
542, in load_entry_point
     return get_distribution(dist).load_entry_point(group, name)
   File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 
2569, in load_entry_point
     return ep.load()
   File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 
2229, in load
     return self.resolve()
   File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 
2235, in resolve
     module = **import**(self.module_name, fromlist=['**name**'], level=0)
   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
   File "<frozen importlib._bootstrap>", line 958, in 
_find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 634, in 
_load_backward_compatible
   File 
"/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_main.py", 
line 9, in <module>
   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
   File "<frozen importlib._bootstrap>", line 958, in 
_find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 634, in 
_load_backward_compatible
   File 
"/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/__init__.py", 
line 9, in <module>
   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
   File "<frozen importlib._bootstrap>", line 958, in 
_find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 634, in 
_load_backward_compatible
   File 
"/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/cli.py", 
line 8, in <module>
AttributeError: module 'click' has no attribute 'MultiCommand'

**Comment by soccadad** [comment]
wright@Maui:~$ sudo pip3 install click --upgrade
[sudo] password for wright: 
The directory '/home/wright/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/wright/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting click
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 3.4MB/s 
Installing collected packages: click
  Found existing installation: click 0.4.45.1+16.10.20160916.0ubuntu1
    Not uninstalling click at /usr/lib/python3/dist-packages, outside environment /usr
  Running setup.py install for click ... done
Successfully installed click-6.6
wright@Maui:~$ onedrive-d start
Loading configuration ... OK
[2016-10-31 16:44:36,887] DEBUG: MainThread: running in daemon node.
Starting onedrive-d ... OK
wright@Maui:~$

**Comment by linuxsoid** [comment]
**heliobentes** and **Xubu**,  The day before yesterday installed a clean Ubuntu 16.04 LTS, and it worked without problems, no errors occurred. I've written [material](http://linuxsoid.com/install-microsoft-onedrive-on-ubuntu), maybe someone will be useful. Thanks for the advice and trying to help.

**Comment by pdave91** [comment]
I had the same issue. Thanks to luk4196's comment, I realized I should add sudo before running `onedrive-d start`

**Comment by chpmoreno** [comment]
I also have this issue in ubuntu 16.04:

`onedrive-d start
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/onedrive_d-1.1.0.dev0-py3.5.egg/onedrive_d/od_main.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/daemonocle-1.0.1-py3.5.egg/daemonocle/cli.py", line 8, in <module>
AttributeError: module 'click' has no attribute 'MultiCommand'
`

**Comment by davidljung** [comment]
I eliminated this traceback error via @heliobentes suggestion:

`sudo pip3 install click --upgrade`

However, that just replaced it with another:

`[2017-02-15 15:12:49,047] CRITICAL: MainThread: onedrive-d may not be installed properly. Exit.`

(Ubuntu 16.10 fresh install of all the prerequisites and clones git repo)

**Comment by Martin819** [comment]
I'm facing the same problem on Ubuntu 16.10

`sudo pip3 install click --upgrade` didn't help.

Any ideas?

**EDIT:**

I've solved the problem about 5 minutes after posting this comment. 

I had to purge and install again `python3-pip` via apt-get:
`sudo apt-get purge python3-pip` --> `sudo apt-get install python3-pip` 

and after that run `sudo pip3 install click --upgrade`.

**Comment by hopicker** [comment]
Unfortunately, I haven’t any idea anymore after breaking my Ubuntu…I have uninstalled Python3 after analyzing the root cause, so new install in side by side mode, and I will try again to install OneDrive.

 

De : Martin Polreich [mailto:notifications@github.com] 
Envoyé : samedi 25 février 2017 12:00
À : xybu/onedrive-d-old <onedrive-d-old@noreply.github.com>
Cc : hopicker <belard.gilles@orange.fr>; Comment <comment@noreply.github.com>
Objet : Re: [xybu/onedrive-d-old] Error when running sync OneDrive (#214)

 

I'm facing the same problem on Ubuntu 16.10

sudo pip3 install click --upgrade didn't help.

Any idead?

**Comment by jdgwf** [comment]
This worked for me Ubuntu 16.04:  `sudo apt-get remove python3-click-package`
then... `sudo pip3 install click` to be sure that the latest libs are installed

Pretty sure it's because of the dist version of click.
