### ISSUE TITLE
onedrive-d  not running

### ISSUE THREAD

**Issue by MZJameSun** [xybu/onedrive-d-old#248]
When I type "onedrive-d start", I can receive "Starting onedrive-d ... OK"
But when I type "onedrive-d status", the terminal told me "onedrive-d -- not running"
Can you help me?

**Comment by Satone7** [comment]
I have the same issue.
And I do onedrive-d start --debug: 

```
satone@Aliyun:~/OneDrive$ onedrive-d start --debug
Loading configuration ... OK
[2019-11-08 18:00:36,838] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
[2019-11-08 18:00:36,951] DEBUG: thread_mgr: started.
[2019-11-08 18:00:36,985] DEBUG: MainThread: daemon started.
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 11, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/cli.py", line 57, in subcommand
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 608, in do_action
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 477, in start
  File "/usr/local/lib/python3.6/dist-packages/daemonocle-1.0.1-py3.6.egg/daemonocle/core.py", line 399, in _run
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_main.py", line 36, in main
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_mon_cli.py", line 112, in start
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_mon_cli.py", line 48, in load_token
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_onedrive_api.py", line 247, in get_property
  File "/usr/local/lib/python3.6/dist-packages/onedrive_d-1.1.0.dev0-py3.6.egg/onedrive_d/od_onedrive_api.py", line 115, in parse_response
onedrive_d.od_onedrive_api.OneDriveAPIException: This API is no longer supported. Please see https://aka.ms/livesdkmigration for information about migrating your application to Microsoft Graph. (api_deprecated)
[2019-11-08 18:00:37,880] DEBUG: MainThread: cleaning up.
All children are gone. Parent is exiting...
```

**Comment by kafkialand** [comment]
The same 

 onedrive-d start --debug
Loading configuration ... OK
[2020-01-13 22:12:20,406] DEBUG: MainThread: running in debug mode.
Starting onedrive-d ... OK
[2020-01-13 22:12:20,459] DEBUG: thread_mgr: started.
[2020-01-13 22:12:20,485] DEBUG: MainThread: daemon started.
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 11, in <module>
    load_entry_point('onedrive-d==1.1.0.dev0', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python3.7/dist-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/Click-7.0-py3.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/daemonocle-1.0.1-py3.7.egg/daemonocle/cli.py", line 57, in subcommand
  File "/usr/local/lib/python3.7/dist-packages/daemonocle-1.0.1-py3.7.egg/daemonocle/core.py", line 608, in do_action
  File "/usr/local/lib/python3.7/dist-packages/daemonocle-1.0.1-py3.7.egg/daemonocle/core.py", line 477, in start
  File "/usr/local/lib/python3.7/dist-packages/daemonocle-1.0.1-py3.7.egg/daemonocle/core.py", line 399, in _run
  File "/usr/local/lib/python3.7/dist-packages/onedrive_d-1.1.0.dev0-py3.7.egg/onedrive_d/od_main.py", line 36, in main
  File "/usr/local/lib/python3.7/dist-packages/onedrive_d-1.1.0.dev0-py3.7.egg/onedrive_d/od_mon_cli.py", line 112, in start
  File "/usr/local/lib/python3.7/dist-packages/onedrive_d-1.1.0.dev0-py3.7.egg/onedrive_d/od_mon_cli.py", line 48, in load_token
  File "/usr/local/lib/python3.7/dist-packages/onedrive_d-1.1.0.dev0-py3.7.egg/onedrive_d/od_onedrive_api.py", line 247, in get_property
  File "/usr/local/lib/python3.7/dist-packages/onedrive_d-1.1.0.dev0-py3.7.egg/onedrive_d/od_onedrive_api.py", line 115, in parse_response
onedrive_d.od_onedrive_api.OneDriveAPIException: This API is no longer supported. Please see https://aka.ms/livesdkmigration for information about migrating your application to Microsoft Graph. (api_deprecated)
[2020-01-13 22:12:20,787] DEBUG: MainThread: cleaning up.
All children are gone. Parent is exiting...

**Comment by jdsvg** [comment]
Hello everyone. Has anyone managed to find the solution to this problem? Thank you

**Comment by ArchibaldChain** [comment]
The same problem

**Comment by susanalandau** [comment]
The same problem, has anyone managed to solve this problem???

**Comment by ghost** [comment]
Hi everyone is there a solution to this error yet ?

**Comment by susanalandau** [comment]
Not al all, I still can not make onedrive-d work. the same error is
happening.
I would appreciate a lot help

best

Susana
