### ISSUE TITLE
Error Running ./install.sh install Command

### ISSUE THREAD

**Issue by PcBrewer** [xybu/onedrive-d-old#250]

**Comment by PcBrewer** [comment]
I got the the part of the install where I was running the "./install.sh install" command and got this error"  linux-modules-extra-4.15.0-51-generic melt
  oxygen-icon-theme screen-resolution-extra
  x11proto-dri2-dev x11proto-gl-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'"  

Any suggestions?  Thank You.

**Comment by PcBrewer** [comment]
I got the the part of the install where I was running the "./install.sh install" command and got this error"  linux-modules-extra-4.15.0-51-generic melt
  oxygen-icon-theme screen-resolution-extra
  x11proto-dri2-dev x11proto-gl-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'"  

Any suggestions?  Thank You.

**Comment by MichelHanzen** [comment]
Same problem:
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

**Comment by MichelHanzen** [comment]
Solution:
sudo apt-get install python3-setuptools
and then: 
./install.sh install
