### ISSUE TITLE
Error after Authentication

### ISSUE THREAD

**Issue by kumarharsh** [xybu/onedrive-d-old#35]
The application does not proceed after the OAuth page redirects. This is the error:
(Could be an error with the python-onedrive package?

TypeError: **init**() got an unexpected keyword argument 'ssl_version'

**Comment by xybu** [comment]
It sounds like some pre-requisite package goes wrong now that onedrive-d does not use SSL explicitly.

Were you able to authenticate the program by command `onedrive-cli auth`?

**Comment by kumarharsh** [comment]
No, i was not. The OAuth dialog opened, I logged-in and authorized the app. then a blank screen on the browser, and the above error thrown in the console.

**Comment by xybu** [comment]
It sounds like one of the pre-requisite packages is going wrong or becomes incompatible with python-onedrive. Could you provide more error message printed on the terminal?

**Comment by kumarharsh** [comment]
``` sh
This is the full error I get while running `onedrive-d` command
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==0.7.1', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.7.1-py2.7.egg/onedrive_d/daemon.py", line 164, in main
    quota = API.get_quota()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 486, in get_quota
    super(OneDriveAPI, self).get_quota()))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 341, in get_quota
    return self('me/skydrive/quota')
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 333, in __call__
    self.auth_get_token()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 522, in auth_get_token
    ret = super(PersistentOneDriveAPI, self).auth_get_token(*argz, **kwz)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 236, in auth_get_token
    res = self.auth_access_data_raw = self._auth_token_request()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 269, in _auth_token_request
    return self.request(self.auth_url_token, method='post', data=post_data)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 160, in request
    res = func(url, **kwz)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 340, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 374, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 155, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 125, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 100, in connection_from_url
    return self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 84, in connection_from_host
    pool = pool_cls(host, port, **self.connection_pool_kw)
TypeError: __init__() got an unexpected keyword argument 'ssl_version'
Exception IOError: (13, 'Permission denied', '/home/khs/.lcrc') in <bound method PersistentOneDriveAPI.__del__ of <onedrive.api_v5.PersistentOneDriveAPI object at 0xa61b98c>> ignored
```

**Comment by xybu** [comment]
For an intermediate solution for the issue, I bet it is to run

```
chmod 755 /home/khs/.lcrc
```

to give write permission to that file.

And you may check out the stuff in wip branch which should work better.

**Comment by marekzyw** [comment]
I have the same problem, however in my case tha last line of the error message is missing. The last line is:

TypeError: **init**() got an unexpected keyword argument 'ssl_version'

I am using the wip branch version

**Comment by xybu** [comment]
The problem on this issue was caused by urllib3 and/or python-onedrive package(s) and as I remember it has been fixed. Could you make sure those packages, and the stuff in wip branch are up-to-date?

**Comment by xybu** [comment]
Check out https://pypi.python.org/pypi/urllib3#id3

**Comment by marekzyw** [comment]
Outdated urllib3 was the issue. Thanks!
