### ISSUE TITLE
Error: Reached stack-limit of 50

### ISSUE THREAD

**Issue by macrosblackd** [xybu/onedrive-d-old#43]
```
Thread-2: executed task: Task(get, /home/<user>/Documents/onedrive/Documents/ConfigImages/back_arrow.png, /Documents/ConfigImages/back_arrow.png)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/components.py", line 121, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/components.py", line 110, in consume
    AGENT.add_message(title = "OneDrive-d", text = t.p2 + " was updated.")
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/daemon.py", line 136, in add_message
    self.last_message.show()
Error: GDBus.Error:org.freedesktop.DBus.GLib.UnmappedError.NotifyOsd.Code1: Reached stack-limit of 50

^CTraceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==0.8', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/daemon.py", line 190, in main
    OneDrive_StatusIcon(API).run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/daemon.py", line 145, in run
    gtk.main()
```

**Comment by macrosblackd** [comment]
Quick research shows that this is something to do with the on-screen notifier. Maybe create an internal queue of updated files and then show those in a batch?

**Comment by xybu** [comment]
Yeah the notifier issue has annoyed me for a while. What I am thinking now is to update the existing message if one is already showing; otherwise issue a new message.

At some point the python-notify package should be retired and we update to https://pypi.python.org/pypi/notify2.

**Comment by xybu** [comment]
Newer versions won't have such messages.
