### ISSUE TITLE
Install on centos 6.5

### ISSUE THREAD

**Issue by mogthesprog** [xybu/onedrive-d-old#51]
I followed the instructions on this post 
http://xmodulo.com/2014/06/sync-microsoft-onedrive-linux.html
And receive this error...

```
Setup is done. You can run onedrive-d command after finishing the settings.
[mgj7@vizpc007 onedrive-d]$ Traceback (most recent call last):
  File "/usr/bin/onedrive-prefs", line 9, in <module>
    load_entry_point('onedrive-d==0.85', 'console_scripts', 'onedrive-prefs')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/onedrive_d-0.85-py2.6.egg/onedrive_d/prefs.py",     line 9, in <module>
    from onedrive import api_v5
  File "/usr/lib/python2.6/site-packages/onedrive/api_v5.py", line 499
    type_filter = {type_filter}
                              ^
SyntaxError: invalid syntax
```

My knowledge of python  (which is relatively basic) tells me that there should be two values in te curly braces on line 499, but I haven't used dictionaries all the often tbh. Is this an issue with my system? or the current release of the onedrive api?

Cheer for any help,

Morgan

**Comment by kleberpna** [comment]
I got exactly the same error when executing the onedrive-d binary:

[kleber@ultra ~]$ onedrive-d
Traceback (most recent call last):
File "/usr/bin/onedrive-d", line 9, in
load_entry_point('onedrive-d==0.85', 'console_scripts', 'onedrive-d')()
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
return ep.load()
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
entry = import(self.module_name, globals(),globals(), ['name'])
File "/usr/lib/python2.6/site-packages/onedrive_d-0.85-py2.6.egg/onedrive_d/daemon.py", line 8, in
import components
File "/usr/lib/python2.6/site-packages/onedrive_d-0.85-py2.6.egg/onedrive_d/components.py", line 17, in
from onedrive import api_v5
File "/usr/lib/python2.6/site-packages/onedrive/api_v5.py", line 500
type_filter = {type_filter}
^
SyntaxError: invalid syntax

And during the installation process, I noticed a compilation error:

Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.zip#md5=89cbc92cda979042533b640b76e6e055
Processing PyYAML-3.11.zip
Running PyYAML-3.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6J1XLg/PyYAML-3.11/egg-dist-tmp-BjZtAQ
build/temp.linux-x86_64-2.6/check_libyaml.c:2:18: error: yaml.h: Arquivo ou diretório não encontrado
build/temp.linux-x86_64-2.6/check_libyaml.c: In function ‘main’:
build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: ‘yaml_parser_t’ undeclared (first use in this function)
build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: (Each undeclared identifier is reported only once
build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: for each function it appears in.)
build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: expected ‘;’ before ‘parser’
build/temp.linux-x86_64-2.6/check_libyaml.c:6: error: ‘yaml_emitter_t’ undeclared (first use in this function)
build/temp.linux-x86_64-2.6/check_libyaml.c:6: error: expected ‘;’ before ‘emitter’
build/temp.linux-x86_64-2.6/check_libyaml.c:8: warning: implicit declaration of function ‘yaml_parser_initialize’
build/temp.linux-x86_64-2.6/check_libyaml.c:8: error: ‘parser’ undeclared (first use in this function)
build/temp.linux-x86_64-2.6/check_libyaml.c:9: warning: implicit declaration of function ‘yaml_parser_delete’
build/temp.linux-x86_64-2.6/check_libyaml.c:11: warning: implicit declaration of function ‘yaml_emitter_initialize’
build/temp.linux-x86_64-2.6/check_libyaml.c:11: error: ‘emitter’ undeclared (first use in this function)
build/temp.linux-x86_64-2.6/check_libyaml.c:12: warning: implicit declaration of function ‘yaml_emitter_delete’
libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
 specify the option --include-dirs or uncomment and
 modify the parameter include_dirs in setup.cfg)
zip_safe flag not set; analyzing archive contents...
Adding PyYAML 3.11 to easy-install.pth file

**Comment by sid351** [comment]
I have the same issue installing on 2014-08-29.  Did you manage to progress at all with this?  

I'm inexperienced with Linux but looking to improve (hence trying to install OneDrive on my CentOS home server) so I'm happy to help test stuff out, if you're happy to be patient and answer stupid Linux questions.

**Comment by mogthesprog** [comment]
Hey fella. I haven't tried actually, i didn't spend much time trying to get it to work though... Sorry for late reply, but manic at the moment. Send me what ouputs and i'll have a look. 

And there's never a dumb linux question bro. Welcome to the fold ;)

But seriously, ask away :)

Cheers,

Morgan

Dragon Creative
Glenthorne,
Rhydyfelin,
Aberystwyth,
SY23 4PX
Phone: 07539370332
E-mail: jones.morgan@dragon-creative.co.uk

**Comment by thejae** [comment]
I have the same error too, here's the full install log. Tagging project owner into this conversation @xybu92 

``` Shell
[james@instance-2 dump]$ sudo ./inst install
Start setting up onedrive-d package.
which: no apt-get in (/sbin:/bin:/usr/sbin:/usr/bin)
Detected package manager: yum
Loaded plugins: downloadonly, fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
 * base: repos.lax.quadranet.com
 * epel: mirrors.tummy.com
 * extras: mirrors.sonic.net
 * remi: remi.kazukioishi.net
 * updates: mirror.rackspace.com
Setting up Install Process
Package git-1.7.1-3.el6_4.1.x86_64 already installed and latest version
Package pywebkitgtk-1.1.6-3.el6.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package inotify-tools.x86_64 0:3.14-1.el6 will be installed
---> Package python-dateutil.noarch 0:1.4.1-6.el6 will be installed
---> Package python-pip.noarch 0:1.3.1-4.el6 will be installed
--> Processing Dependency: python-setuptools for package: python-pip-1.3.1-4.el6.noarch
---> Package rcs.x86_64 0:5.7-37.el6 will be installed
--> Running transaction check
---> Package python-setuptools.noarch 0:0.6.10-3.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                  Arch          Version               Repository   Size
================================================================================
Installing:
 inotify-tools            x86_64        3.14-1.el6            epel         46 k
 python-dateutil          noarch        1.4.1-6.el6           base         84 k
 python-pip               noarch        1.3.1-4.el6           epel        330 k
 rcs                      x86_64        5.7-37.el6            base        173 k
Installing for dependencies:
 python-setuptools        noarch        0.6.10-3.el6          base        336 k

Transaction Summary
================================================================================
Install       5 Package(s)

Total download size: 969 k
Installed size: 3.6 M
Is this ok [y/N]: y
Downloading Packages:
(1/5): inotify-tools-3.14-1.el6.x86_64.rpm               |  46 kB     00:00     
(2/5): python-dateutil-1.4.1-6.el6.noarch.rpm            |  84 kB     00:00     
(3/5): python-pip-1.3.1-4.el6.noarch.rpm                 | 330 kB     00:00     
(4/5): python-setuptools-0.6.10-3.el6.noarch.rpm         | 336 kB     00:00     
(5/5): rcs-5.7-37.el6.x86_64.rpm                         | 173 kB     00:00     
--------------------------------------------------------------------------------
Total                                           230 kB/s | 969 kB     00:04     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : python-setuptools-0.6.10-3.el6.noarch                        1/5 
  Installing : python-pip-1.3.1-4.el6.noarch                                2/5 
  Installing : inotify-tools-3.14-1.el6.x86_64                              3/5 
  Installing : python-dateutil-1.4.1-6.el6.noarch                           4/5 
  Installing : rcs-5.7-37.el6.x86_64                                        5/5 
  Verifying  : rcs-5.7-37.el6.x86_64                                        1/5 
  Verifying  : python-pip-1.3.1-4.el6.noarch                                2/5 
  Verifying  : python-dateutil-1.4.1-6.el6.noarch                           3/5 
  Verifying  : inotify-tools-3.14-1.el6.x86_64                              4/5 
  Verifying  : python-setuptools-0.6.10-3.el6.noarch                        5/5 

Installed:
  inotify-tools.x86_64 0:3.14-1.el6     python-dateutil.noarch 0:1.4.1-6.el6    
  python-pip.noarch 0:1.3.1-4.el6       rcs.x86_64 0:5.7-37.el6                 

Dependency Installed:
  python-setuptools.noarch 0:0.6.10-3.el6                                       

Complete!
Downloading/unpacking python-onedrive from git+https://github.com/mk-fg/python-onedrive.git
  Cloning https://github.com/mk-fg/python-onedrive.git to /tmp/pip-build-root/python-onedrive
  Running setup.py egg_info for package python-onedrive
Installing collected packages: python-onedrive
  Running setup.py install for python-onedrive
    SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/onedrive/conf.py', 27, 21, "        client={'id', 'secret'},\n"))

    SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/onedrive/api_v5.py', 502, 43, '                type_filter = {type_filter}\n'))

    Installing onedrive-cli script to /usr/bin
Successfully installed python-onedrive
Cleaning up...
running install
running bdist_egg
running egg_info
creating onedrive_d.egg-info
writing requirements to onedrive_d.egg-info/requires.txt
writing onedrive_d.egg-info/PKG-INFO
writing top-level names to onedrive_d.egg-info/top_level.txt
writing dependency_links to onedrive_d.egg-info/dependency_links.txt
writing entry points to onedrive_d.egg-info/entry_points.txt
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/onedrive_d
copying onedrive_d/daemon.py -> build/lib/onedrive_d
copying onedrive_d/components.py -> build/lib/onedrive_d
copying onedrive_d/__init__.py -> build/lib/onedrive_d
copying onedrive_d/config.py -> build/lib/onedrive_d
copying onedrive_d/prefs.py -> build/lib/onedrive_d
creating build/lib/onedrive_d/res
copying onedrive_d/res/icon_256.png -> build/lib/onedrive_d/res
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/daemon.py -> build/bdist.linux-x86_64/egg/onedrive_d
creating build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/res/icon_256.png -> build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/components.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/config.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/prefs.py -> build/bdist.linux-x86_64/egg/onedrive_d
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/daemon.py to daemon.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/components.py to components.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/prefs.py to prefs.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
onedrive_d.daemon: module references __file__
creating dist
creating 'dist/onedrive_d-0.85-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing onedrive_d-0.85-py2.6.egg
creating /usr/lib/python2.6/site-packages/onedrive_d-0.85-py2.6.egg
Extracting onedrive_d-0.85-py2.6.egg to /usr/lib/python2.6/site-packages
Adding onedrive-d 0.85 to easy-install.pth file
Installing onedrive-prefs script to /usr/bin
Installing onedrive-d script to /usr/bin

Installed /usr/lib/python2.6/site-packages/onedrive_d-0.85-py2.6.egg
Processing dependencies for onedrive-d==0.85
Searching for notify2
Reading http://pypi.python.org/simple/notify2/
Best match: notify2 0.3
Downloading https://pypi.python.org/packages/source/n/notify2/notify2-0.3.tar.gz#md5=6b2f6400999956652e4c9bc83d87607b
Processing notify2-0.3.tar.gz
Running notify2-0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-f2ChsW/notify2-0.3/egg-dist-tmp-0FdF1I
zip_safe flag not set; analyzing archive contents...
Adding notify2 0.3 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/notify2-0.3-py2.6.egg
Searching for PyYAML
Reading http://pypi.python.org/simple/PyYAML/
Best match: PyYAML 3.11
Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.zip#md5=89cbc92cda979042533b640b76e6e055
Processing PyYAML-3.11.zip
Running PyYAML-3.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pHDAWu/PyYAML-3.11/egg-dist-tmp-UkaSAo
unable to execute gcc: No such file or directory

libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
 specify the option --include-dirs or uncomment and
 modify the parameter include_dirs in setup.cfg)
zip_safe flag not set; analyzing archive contents...
Adding PyYAML 3.11 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/PyYAML-3.11-py2.6-linux-x86_64.egg
Searching for urllib3
Reading http://pypi.python.org/simple/urllib3/
Best match: urllib3 1.9.1
Downloading https://pypi.python.org/packages/source/u/urllib3/urllib3-1.9.1.tar.gz#md5=c9358c5a85dd6aa3942f5121efed064d
Processing urllib3-1.9.1.tar.gz
Running urllib3-1.9.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jC4ez8/urllib3-1.9.1/egg-dist-tmp-6F3nKj
warning: no previously-included files matching '*' found under directory 'docs/_build'
zip_safe flag not set; analyzing archive contents...
Adding urllib3 1.9.1 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/urllib3-1.9.1-py2.6.egg
Searching for requests
Reading http://pypi.python.org/simple/requests/
Best match: requests 2.4.1
Downloading https://pypi.python.org/packages/source/r/requests/requests-2.4.1.tar.gz#md5=931461f761c70708c46ea65b7889da58
Processing requests-2.4.1.tar.gz
Running requests-2.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rhyQtx/requests-2.4.1/egg-dist-tmp-uSN57v
Adding requests 2.4.1 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/requests-2.4.1-py2.6.egg
Searching for python-onedrive==14.09.3
Best match: python-onedrive 14.09.3
Adding python-onedrive 14.09.3 to easy-install.pth file
Installing onedrive-cli script to /usr/bin

Using /usr/lib/python2.6/site-packages
Finished processing dependencies for onedrive-d==0.85
Setup is done. You can run onedrive-d command after finishing the settings.
[james@instance-2 dump]$ Traceback (most recent call last):
  File "/usr/bin/onedrive-prefs", line 9, in <module>
    load_entry_point('onedrive-d==0.85', 'console_scripts', 'onedrive-prefs')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/onedrive_d-0.85-py2.6.egg/onedrive_d/prefs.py", line 9, in <module>
    from onedrive import api_v5
  File "/usr/lib/python2.6/site-packages/onedrive/api_v5.py", line 502
    type_filter = {type_filter}
                              ^
SyntaxError: invalid syntax


```

**Comment by xybu** [comment]
May you go to mk-fg/python-onedrive for the error in api_v5? Looks like it doesn't work well with Py2.6

**Comment by thejae** [comment]
Thanks for your fast reply! same error with the version from mk-fg/python-onedrive

```
[james@instance-2 onedrive]$ sudo onedrive-cli
Traceback (most recent call last):
  File "/usr/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.09.3', 'console_scripts', 'onedrive-cli')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/python_onedrive-14.09.3-py2.6.egg/onedrive/cli_tool.py", line 17, in <module>
    from onedrive import api_v5, conf
  File "/usr/lib/python2.6/site-packages/python_onedrive-14.09.3-py2.6.egg/onedrive/api_v5.py", line 502
    type_filter = {type_filter}
                              ^
SyntaxError: invalid syntax
```

**Comment by thejae** [comment]
I just tried install Python 3.3.2 and then 3.4.1, both exhibit the following error:

```
[james@instance-2 dump]$ python --version
Python 3.4.1
[james@instance-2 dump]$ ./inst install
Start setting up onedrive-d package.
which: no apt-get in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/james/bin)
Detected package manager: yum
  File "/usr/bin/yum", line 30
    except KeyboardInterrupt, e:
                            ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
rm: cannot remove `build': No such file or directory
rm: cannot remove `dist': No such file or directory
rm: cannot remove `onedrive_d.egg-info': No such file or directory
Setup is done. You can run onedrive-d command after finishing the settings.
[james@instance-2 dump]$ Traceback (most recent call last):
  File "/usr/bin/onedrive-prefs", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

Can you tell us what version of Python that worked for you? I'll test it.

**Comment by xybu** [comment]
I test with Py3.4 on Xubuntu 14.04.01 64-bit. The inst script was never tested on cent before.

For the issue you posted, it is yum that doesn't work on Py3:
http://stackoverflow.com/questions/11213520/yum-crashed-with-keyboard-interrupt-error
http://www.cprogramdevelop.com/5051651/

You should be able to call `python3` directly, _without_ changing the default Python version to Py3k.
And `pip` should be `pip3`, unless you are uninstalling the old version.
Something is not good somewhere...

**Comment by thejae** [comment]
Yea I figured out that I had broken `yum` when I installed Python3. Now I can't seem to be able to fix it lol I'll deploy another VM later tonight and use your suggestion (install py3 using the `make altinstall` flag).

I'll post back with any updates.

**Comment by zemmali** [comment]
> Just Update #!/usr/bin/python to #!/usr/bin/python2.7 in **/bin/yum**

#!/usr/bin/python2.7
import sys
try:
    import yum
except ImportError:
    print >> sys.stderr, """\
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   %s

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
%s

If you cannot solve this problem yourself, please go to
the yum faq at:
  http://yum.baseurl.org/wiki/Faq

""" % (sys.exc_value, sys.version)
    sys.exit(1)

sys.path.insert(0, '/usr/share/yum-cli')
try:
    import yummain
    yummain.user_main(sys.argv[1:], exit_code=True)
except KeyboardInterrupt, e:
    print >> sys.stderr, "\n\nExiting on user cancel."
    sys.exit(1)
