### ISSUE TITLE
Fedora 20: Exception during initial sync

### ISSUE THREAD

**Issue by Hades32** [xybu/onedrive-d-old#61]
started onedrive-d manuall and got this stacktrace. Seems there is a Problem in handling umlauts. (\xc3\x9c is supposed to be a 'Ü')

Thread-2: /home/hades32/OneDrive/Familienbereich/Background (1).jpg Old_mtime is 1409557306.54 and new_mtime is 1352499184 and is changed to 1352499184.0
Thread-2: executed task: Task(get, /home/hades32/OneDrive/Familienbereich/Background (1).jpg, /Familienbereich/Background (1).jpg)
Thread-2: /home/hades32/OneDrive/Familienbereich/TUID_19173760_1_thomas.pdf Old_mtime is 1409557311.82 and new_mtime is 1370628636 and is changed to 1370628636.0
Thread-2: executed task: Task(get, /home/hades32/OneDrive/Familienbereich/TUID_19173760_1_thomas.pdf, /Familienbereich/TUID_19173760_1_thomas.pdf)
Traceback (most recent call last):
  File "/usr/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/lib/python2.7/site-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/lib/python2.7/site-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/lib/python2.7/site-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/lib/python2.7/site-packages/onedrive/api_v5.py", line 482, in resolve_path
    raise DoesNotExists(root_id, path[i:])
onedrive.api_v5.DoesNotExists: (u'folder.1fd9b66b81b450c4.1FD9B66B81B450C4!833', [u'\u0102\x9cbergabeprotokol.tif'])
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/lib/python2.7/site-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] No such file or directory: '/home/hades32/OneDrive/Familienbereich/\xc3\x9cbergabeprotokol.tif'

**Comment by Hades32** [comment]
This doesn't seem to be a problem when the umlaut is on a folder name. It then is NOT escaped and seems to work.

**Comment by xybu** [comment]
For UTF-8 issues, please check if 1.0-dev works properly. Thank you!
