### ISSUE TITLE
UBUNTU problems with some characters in filenames outside latin alphabet

### ISSUE THREAD

**Issue by ljasinskipl** [xybu/onedrive-d-old#63]
Can't sync some files. 

`Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 482, in resolve_path
    raise DoesNotExists(root_id, path[i:])
onedrive.api_v5.DoesNotExists: (u'folder.af9e3be076e98b4e.AF9E3BE076E98B4E!937', [u'Modlitwa do Matki Boskiej Cz\xc4\x99stochowskiej.docx'])
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Nie ma takiego pliku ani katalogu: '/home/ljasinskipl/Cloud/Microsoft OneDrive/MBNP/Modlitwa do Matki Boskiej Cz\xc4\x99stochowskiej.docx'`

**Comment by xybu** [comment]
The version 1.0-dev uses Py3k and my own API layer. It should improve UTF-8 handling way better than the old version. If possible please check it out.
