### ISSUE TITLE
Installed with ./setup.sh inst but no executables found

### ISSUE THREAD

**Issue by RoFz** [xybu/onedrive-d-old#65]
Just installed onedrive-d on Ubuntu 14.04 using ' ./setup.sh inst' but the onedrive-d or onedrive-pref executables are nowhere to be found in the system. I can see that some files are being generated on /usr/local/lib/python3.4/dist-packages, but there are no executables.

root@Rodrigo-PC:~/onedrive-d-1.0-dev# ls /usr/local/lib/python3.4/dist-packages/certifi-14.05.14-py3.4.egg  onedrive_d-1.0_dev-py3.4.egg
easy-install.pth            Send2Trash-1.3.0-py3.4.egg
root@Rodrigo-PC:~/onedrive-d-1.0-dev#

Installation log:
root@Rodrigo-PC:~/onedrive-d-1.0-dev# ./setup.sh inst
Reading package lists... Done
Building dependency tree  
Reading state information... Done
git is already the newest version.
inotify-tools is already the newest version.
python3-pip is already the newest version.
python3-gi is already the newest version.
The following packages were automatically installed and are no longer required:
  linux-headers-generic linux-image-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating onedrive_d.egg-info
writing dependency_links to onedrive_d.egg-info/dependency_links.txt
writing onedrive_d.egg-info/PKG-INFO
writing top-level names to onedrive_d.egg-info/top_level.txt
writing requirements to onedrive_d.egg-info/requires.txt
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/onedrive_d
copying onedrive_d/pref_cmd.py -> build/lib/onedrive_d
copying onedrive_d/pref.py -> build/lib/onedrive_d
copying onedrive_d/observer_gtk.py -> build/lib/onedrive_d
copying onedrive_d/observer_dummy.py -> build/lib/onedrive_d
copying onedrive_d/test_live_api.py -> build/lib/onedrive_d
copying onedrive_d/daemon.py -> build/lib/onedrive_d
copying onedrive_d/config.py -> build/lib/onedrive_d
copying onedrive_d/main.py -> build/lib/onedrive_d
copying onedrive_d/**init**.py -> build/lib/onedrive_d
copying onedrive_d/live_api.py -> build/lib/onedrive_d
copying onedrive_d/pref_gtk.py -> build/lib/onedrive_d
copying onedrive_d/logger.py -> build/lib/onedrive_d
copying onedrive_d/setup.py -> build/lib/onedrive_d
creating build/lib/onedrive_d/res
copying onedrive_d/res/icon_256.png -> build/lib/onedrive_d/res
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref_cmd.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/observer_gtk.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/observer_dummy.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/test_live_api.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/daemon.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/config.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/main.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/**init**.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/live_api.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref_gtk.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/logger.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/setup.py -> build/bdist.linux-x86_64/egg/onedrive_d
creating build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/res/icon_256.png -> build/bdist.linux-x86_64/egg/onedrive_d/res
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref_cmd.py to pref_cmd.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref.py to pref.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/observer_gtk.py to observer_gtk.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/observer_dummy.py to observer_dummy.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/test_live_api.py to test_live_api.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/daemon.py to daemon.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/config.py to config.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/main.py to main.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/live_api.py to live_api.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref_gtk.py to pref_gtk.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/logger.py to logger.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/setup.py to setup.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
onedrive_d.**pycache**.observer_gtk.cpython-34: module references **file**
onedrive_d.**pycache**.setup.cpython-34: module references **file**
creating dist
creating 'dist/onedrive_d-1.0_dev-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing onedrive_d-1.0_dev-py3.4.egg
creating /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg
Extracting onedrive_d-1.0_dev-py3.4.egg to /usr/local/lib/python3.4/dist-packages
Adding onedrive-d 1.0-dev to easy-install.pth file

Installed /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg
Processing dependencies for onedrive-d==1.0-dev
Searching for Send2Trash==1.3.0
Best match: Send2Trash 1.3.0
Processing Send2Trash-1.3.0-py3.4.egg
Send2Trash 1.3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/Send2Trash-1.3.0-py3.4.egg
Searching for certifi==14.05.14
Best match: certifi 14.05.14
Processing certifi-14.05.14-py3.4.egg
certifi 14.05.14 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/certifi-14.05.14-py3.4.egg
Searching for urllib3==1.7.1
Best match: urllib3 1.7.1
urllib3 1.7.1 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Searching for requests==2.2.1
Best match: requests 2.2.1
requests 2.2.1 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Finished processing dependencies for onedrive-d==1.0-dev
running clean

Please issue command 'onedrive-pref [--no-gui]' to configure the app,
and then issue command 'onedrive-d [--no-gui]' to start the daemon.
All operations finished.
root@Rodrigo-PC:~/onedrive-d-1.0-dev# 

The problem:

root@Rodrigo-PC:~/onedrive-d-1.0-dev# onedrive-d
onedrive-d: command not found
root@Rodrigo-PC:~/onedrive-d-1.0-dev# onedrive-pref
onedrive-pref: command not found
root@Rodrigo-PC:~/onedrive-d-1.0-dev#

**Comment by xybu** [comment]
The source code for 1.0 is just for testing. The setup script does not add shortcuts of the scripts to the system. To run the program, run the python script directly.

./onedrive_d/main.py

And note that no GUI is implemented and one should use the cli interface at this stage.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by kumarharsh** [comment]
I'd second this issue.
1. It's not giving any clue as to where to find the onedrive executable.
2. There is no `config.json` file in the `~/.onedrive` folder. If I make one, what keys should be there?
   I just added this to the config:

``` json
{
  "log_path": "/home/me/.onedrive"
}
```
1. When I run the `./onedrive_d/pref_gtk.py` file, it just says:

```
[2014-10-28T17:28:11+0530] MainThread   CRITICAL: Failed to open path "/home/me/.onedrive" for logging. Use stderr instead.
```

but still, outputs nothing.
1. When I run the `./onedrive_d/pref.py` file, it says the same thing, but opens up a window which is absolutely blank gray. I waited for 5 minutes, but still no activity.

It's sad that I've had no luck with this project yet... Really looking fwd to a good stable version which runs...

**Comment by xybu** [comment]
No shortcut created on the system because the program isn't that mature.

To set up the configuration files,
onedrive_d/pref.py --no-gui

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by alrekr** [comment]
Same problem on Ubuntu 14.10. 
I made dir ~/onedrive-attempt/ and cloned into that using 

```
$ git clone https://github.com/xybu/onedrive-d
```

and installed using 

```
$ ./setup.sh inst
```

Trying to setup config fails:

```
$ onedrive-pref
onedrive-pref: command not found
```

and 

```
$ ./onedrive_d/pref.py --no-gui
Traceback (most recent call last):
  File "./onedrive_d/pref.py", line 8, in <module>
    import config
  File "/home/alrekr/onedrive-attempt/onedrive-d/onedrive_d/config.py", line 117, in <module>
    with open(APP_CONFIG_FILE_PATH, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/alrekr/.onedrive/config.json'
```

The remove parameter doesn't work either:

```
$ ./setup.sh remove
Removing Python 2 version of onedrive_d, if any.
sudo: pip: command not found
```

**Comment by kumarharsh** [comment]
For removing, open the setup.sh file, and comment out the line which removes the python2 version.

**Comment by kumarharsh** [comment]
@xybu I was able to run the prefs correctly. Thanks for the suggestion. The config was successful, but I'm not able to run the `main.py` (I'm assuming that main.py is the main client?) While running the client, here is what I get:

``` shell
$ ./onedrive_d/main.py --no-gui
```

``` shell
Exception in thread worker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/me/repos/onedrive-d/onedrive_d/daemon.py", line 401, in run
    f.write(self.api.get(entry_id = row['remote_id']))
  File "/home/me/repos/onedrive-d/onedrive_d/live_api.py", line 293, in get
    ret = request.json()
NameError: name 'request' is not defined

```

**Comment by xybu** [comment]
Either python3-requests is not installed or I have a typo somewhere. Let me check the code later today.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by xybu** [comment]
Yeah the issue was I made a typo. Fixed at ce53c40a23a1ca4535b476f0cadb2a09de3d722d. Sorry about that.

**Comment by kumarharsh** [comment]
Now, there is another error (further down the chain):

``` shell
$ ./onedrive_d/main.py --no-gui
```

``` shell
Exception in thread worker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/me/repos/onedrive-d/onedrive_d/daemon.py", line 401, in run
    f.write(self.api.get(entry_id = row['remote_id']))
  File "/home/me/repos/onedrive-d/onedrive_d/live_api.py", line 297, in get
    else: raise ProtocolError(ret)
live_api.ProtocolError: "request_url_invalid: Resource type 'notebook' doesn't support the path 'content'."
```

``` shell
Exception in thread worker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/me/repos/onedrive-d/onedrive_d/daemon.py", line 405, in run
    self.do_postwork(row)
  File "/home/me/repos/onedrive-d/onedrive_d/daemon.py", line 364, in do_postwork
    self.update_entry(new_info)
  File "/home/me/repos/onedrive-d/onedrive_d/daemon.py", line 305, in update_entry
    update_entry(self.conn, entry)
  File "/home/me/repos/onedrive-d/onedrive_d/daemon.py", line 109, in update_entry
    '(:parent_path, :name, :id, :parent_id, :type, :size, :client_updated_time, :status)', entry)
sqlite3.OperationalError: database is locked
```

**Comment by xybu** [comment]
I guess the `notebook` file is an OneNote link?

**Comment by kumarharsh** [comment]
<del>It's possible. yes. I'll take a look.</del>

Yes, indeed. But I think the daemon is having trouble with onenote files. All my onenote files have been overwritten by a "<filename> (<MyCompName> Newer)" plaintext file of 0 bytes.

**Comment by kumarharsh** [comment]
OK, the daemon is running... Although I don't get any sense of activity unless it throws an exception :P 

``` shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/me/repos/onedrive-d/onedrive_d/daemon.py", line 466, in run
    self.reset_task(row)
  File "/home/me/repos/onedrive-d/onedrive_d/daemon.py", line 346, in reset_task
    self.cursor.execute('UPDATE tasks SET priority=1 WHERE id=?', (row['id'],))
NameError: name 'row' is not defined
```

**Comment by xybu** [comment]
For the OneNote thing, it is causing headache so far. Linux doesn't have file ext like .url in Windows. We can't determine if it is an OneNote entry merely from file size either... Fetching the file content sometimes throw ProtocolError, but size=0&&Error still can't guarantee an OneNote link...

For the new bug you reported... Well, I must have been dumb recently... Check out commit 6b54f2488d7df3a27d1f2fc0e6a5c91235f16ef3

**Comment by kumarharsh** [comment]
Oh... lol for the last line :P
I'll check out the changes :)

**Comment by xybu** [comment]
Now the code in `future` branch (version TBD) will create the shortcuts. Robust enough for some beta testing.
