### ISSUE TITLE
Installed, connected, but no file in folder

### ISSUE THREAD

**Issue by pissarev** [xybu/onedrive-d-old#67]
Hello,

I installed with this commands:

wget https://github.com/xybu92/onedrive-d/archive/master.zip
unzip master.zip 
cd onedrive-d-master/
sudo ./inst install

and here's the list running onedrive-d:

p@p-Latitude-D630:~$ onedrive-d
Thread-1 (worker): initiated
Thread-2 (worker): initiated
main: All threads should have started.
 Thread-3: Start scanning dir  ("/home/p/OneDrive")
Thread-5: Start scanning dir /ASS ("/home/p/OneDrive/ASS")
Thread-6: Start scanning dir /Documenti ("/home/p/OneDrive/Documenti")
Thread-3: done.
Thread-7: Start scanning dir /Immagini ("/home/p/OneDrive/Immagini")
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 153, in run
    self.pre_merge()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 165, in pre_merge
    if exc.errno == errno.EEXIST and os.path.isdir(self._localPath):
NameError: global name 'errno' is not defined

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 153, in run
    self.pre_merge()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 165, in pre_merge
    if exc.errno == errno.EEXIST and os.path.isdir(self._localPath):
NameError: global name 'errno' is not defined

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 153, in run
    self.pre_merge()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 165, in pre_merge
    if exc.errno == errno.EEXIST and os.path.isdir(self._localPath):
NameError: global name 'errno' is not defined

Waiter quit.
Local_mon: >>>Setting up watches.  Beware: since -r was given, this may take a while!

Local_mon: >>>Watches established.

[]

running onedrive-prefs tells that I'm connected to the account.
The terminal remains active, and as I said, no file is downloaded in the /home/p/OneDrive folder

**Comment by xybu** [comment]
There seems OSError accessing the local dir.

**Comment by pissarev** [comment]
Great tip!
I created another folder and it works!
Thank you very much.
P.S. I'll wait for the notification icon on the bar (like dropbox)
