### ISSUE TITLE
utf8 issue in filenames?

### ISSUE THREAD

**Issue by leolivier** [xybu/onedrive-d-old#70]
Hi Xybu
I still have some problems and I am wondering if it is an utf8 issue.
I get errors like these:
Thread-Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 482, in resolve_path
    raise DoesNotExists(root_id, path[i:])
onedrive.api_v5.DoesNotExists: (u'folder.31100c4dd70e082d.31100C4DD70E082D!1305', [u'd\u0102\u0160cembre 2010', u'P1030341.JPG'])
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 482, in resolve_path
    raise DoesNotExists(root_id, path[i:])
onedrive.api_v5.DoesNotExists: (u'folder.31100c4dd70e082d.31100C4DD70E082D!1305', [u'd\u0102\u0160cembre 2010', u'P1030339.JPG'])
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 482, in resolve_path
    raise DoesNotExists(root_id, path[i:])
onedrive.api_v5.DoesNotExists: (u'folder.31100c4dd70e082d.31100C4DD70E082D!1305', [u'd\u0102\u0160cembre 2010', u'P1030338.JPG'])
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/data/OneDrive/Photos/2010/d\xc3\xa9cembre 2010/P1030339.JPG'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/data/OneDrive/Photos/2010/d\xc3\xa9cembre 2010/P1030338.JPG'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/data/OneDrive/Photos/2010/d\xc3\xa9cembre 2010/P1030341.JPG'

Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 482, in resolve_path
    raise DoesNotExists(root_id, path[i:])
onedrive.api_v5.DoesNotExists: (u'folder.31100c4dd70e082d.31100C4DD70E082D!1305', [u'd\u0102\u0160cembre 2010', u'P1030340.JPG'])
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/data/OneDrive/Photos/2010/d\xc3\xa9cembre 2010/P1030340.JPG'

(Aucun fichier ou dossier de ce type means No such file or directory)
"d\xc3\xa9cembre" in the file name should be "décembre" with an e acute.
No file has been synchronized in this directory (which exists on the file system)...

**Comment by xybu** [comment]
It looked like the UTF8 chars were encoded in the path and Python cannot properly fetch them.

If you have time, could you try testing 1.0-dev which has built-in support with Unicode chars?

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by leolivier** [comment]
Hi Xiangyu,
it's me again. I installed the dev branch as requested but still get the same errors. 
But I'm not sure that the dev branch installation replaced the old one. It seems I still use the same packages in traces below (0.85). 
Can you confirm this and, if necessary, tell me how to get rid of the old version?
Thank you

  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 482, in resolve_path
    raise DoesNotExists(root_id, path[i:])
onedrive.api_v5.DoesNotExists: (u'folder.31100c4dd70e082d.31100C4DD70E082D!1305', [u'd\u0102\u0160cembre 2010', u'P1030338.JPG'])
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/data/OneDrive/Photos/2010/d\xc3\xa9cembre 2010/P1030338.JPG'

or

Thread-1: /data/OneDrive/Images/Pellicule/20140923_163246_Android.png Old_mtime is 1412332742.05 and new_mtime is 1411482766 and is changed to 1Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 482, in resolve_path
    raise DoesNotExists(root_id, path[i:])
onedrive.api_v5.DoesNotExists: (u'folder.31100c4dd70e082d.31100C4DD70E082D!1305', [u'd\u0102\u0160cembre 2010', u'P1030339.JPG'])
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/data/OneDrive/Photos/2010/d\xc3\xa9cembre 2010/P1030339.JPG'

**Comment by leolivier** [comment]
I finally uninstalled the master version, the 1.0-dev version (onedrive-d, onedrive-cli and onedrive-prefs was not uninstalled by the master uninstall so I removed them manually from /usr/local/bin).
Then I  reinstalled the 1.0-dev version. It seems to run well but unfortunately, this doesn't seem to install neither onedrive-d nor onedrive-pref.
I found a in the dump directory a onedrive-d shell script, but its not copied anywher by the install and I didn't find any onedrive-pref anywhere...
Any clue?

**Comment by xybu** [comment]
`setup.sh remove` gets you rid of all the stuff, including old version. I don't have those shortcuts created to system because the version still has a long long way to go, and the command-line args are not well defined yet. If you check you can see lines 48 to 50 of https://github.com/xybu/onedrive-d/blob/1.0-dev/onedrive_d/setup.py are intentionally commented out (and actually they now point to wrong addresses because of the changes in the software entry points).

To run the program manually,

```
cd onedrive_d
./pref.py --no-gui
./main.py
```

The `dump` dir is a copy of the old stuff in `master` (0.85) branch for my personal convenience...

The shell script you mentioned was the script to create the daemon. I plan to change the daemon mechanism as #62  mentioned, but the details haven't been decided. Too busy with my coursework to get back to onedrive-d...

**Comment by leolivier** [comment]
OK, thank you (but as far as I can see, the remove stuff only cleans the 
python packages but not the things in /usr/local/bin).
Anyway, I started the pref and the daemon the way you said and it seems 
that the utf8 problem no longer appear BUT no download or upload are done.
I attach the log of the execution to this email.
1) Although it says that several files have to be uploaded, they are not 
(see /data/OneDrive/Photos/2014/Jazzie/ for instance)
2) No files are downloaded although, hundreds of them should be (for 
instance in /data/OneDrive/Photos/2014/ and all subdirectories)

At the end of the scan, it starts back at the beginning but then after a 
few minutes, the access token expires and nothing more happens...

**Comment by leolivier** [comment]
Hi again,
I had a look at the sqlite database and the "entries" table is full of rows of files in get status  (>9000 rows). 
But I find only one line in the tasks table (one put)
So that, I think the scan is ok but the gets are not done...

**Comment by xybu** [comment]
pip should clean all the traces of the package including shortcuts, but let me double check.

The pulling interval (DAEMON_PULL_INTERVAL, in seconds, in main.py, line 10) is set very small for testing's purpose. It should practically 5*(the time used for one synchrnonization).

All entry rows added but only one task row... Either other task rows have been consumed and deleted or any exception happened to the process and killed the worker threads. But if the task row was consumed, the corresponding entry table should have status "sync". Could you run the program and see if any exception happens?

**Comment by Dutchglory** [comment]
cool  :+1:

**Comment by leolivier** [comment]
I changed the pulling interval to 250 and restarted the daemon. But what 
do you mean by "the time used for one synchronisation"? The average time 
for down/uploading one file?
It seems that, anyway, having changed the time doesn't trigger any 
upload or download...
The network traffic remains desesperatly flat...
At the end, I still get a "request token expired" exception and when I 
look at the base I have
in entries: 5267 get rows, 1 put row, around 4000 synced rows (for files 
that where synced by the "master" branch of onedrive_d)
in tasks: 5660 get, around 10 put tasks...
So, hard to understand...
But, no file has been downloaded or uploaded as far as I can see. Or, 
maybe only one or two and the workers die just after so that nothing 
else is done?

I found the following exceptions:
[2014-10-04T18:09:03+0200] syncer    INFO: syncing 
/data/OneDrive/Images/Pellicule/
Exception in thread worker-0:
Traceback (most recent call last):
   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
     self.run()
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 410, in run
     local_path = row['local_path'])
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/live_api.py", 
line 278, in put
     raise ProtocolError(ret)
live_api.ProtocolError: 'server_internal_error: An error occurred while 
performing the action. Try again later.'

then

[2014-10-04T18:17:07+0200] syncer    INFO: syncing 
/data/OneDrive/Photos/2005/juillet 2005/
Exception in thread worker-1:
Traceback (most recent call last):
   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
     self.run()
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 411, in run
     self.do_postwork(row, update)
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 356, in do_postwork
     self.update_entry(new_info)
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 303, in update_entry
     update_entry(self.conn, entry)
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 107, in update_entry
     '(:parent_path, :name, :id, :parent_id, :type, :size, 
:client_updated_time, :status)', entry)
sqlite3.OperationalError: database is locked

and

[2014-10-04T19:04:45+0200] syncer    INFO: syncing 
/data/OneDrive/Photos/2012/été/
Exception in thread syncer:
Traceback (most recent call last):
   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
     self.run()
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 674, in run
     self.merge_dir(entry)
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 516, in merge_dir
     all_remote_items = self.api.list_entries(remote_path)
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/live_api.py", 
line 194, in list_entries
     return self.parse_response(r, ProtocolError)['data']
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/live_api.py", 
line 64, in parse_response
     raise error(ret)
live_api.ProtocolError: 'request_token_expired: The access token that 
was provided has expired.'

I attach the full trace file to this mail...

**Comment by xybu** [comment]
"DAEMON_PULL_INTERVAL" is the interval between two deep synchronization events (fetch and check all the details, just like what the program does at the very beginning). For example, if it takes 1min from fetching file list of your OneDrive root to downloading / uploading all the files to get synced, this parameter should be set larger than 1min otherwise the program may start a new deep sync immediately after one is finished.

I don't know why but somehow OneDrive server does not handle the requests sent by onedrive-d:

```
live_api.ProtocolError: 'server_internal_error: An error occurred while performing the action. Try again later.'
```

which means the server returned "server_internal_error" with description "An error occurred while performing the action. Try again later.".

May this be due to that the requests are too frequent? Not sure if adding another interval parameter can mitigate it.

This unexpected error kills the worker and the remaining workers get killed too because of the sqlite3 db lock.

On the last piece of the log, "request_token_expired" happens in the middle of the execution. As I recall the token expires every 30min or every 1h. Some code should be added to verify the token. I can deal with this one.
