### ISSUE TITLE
invalid_grant error on authentication

### ISSUE THREAD

**Issue by ghost** [xybu/onedrive-d-old#72]
I have Linux Mint 17 Cinnamon and have tried both the _master and _wip versions. For authentication I have tried both GUI and CLI. I successfully log in to my onedrive account, but when I click on the button to grant permissions (or enter the url after redirects), it terminates with the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/prefs.py", line 53, in page_loaded
    self.liveAPI.auth_get_token()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 527, in auth_get_token
    ret = super(PersistentOneDriveAPI, self).auth_get_token(_argz, *_kwz)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 237, in auth_get_token
    res = self.auth_access_data_raw = self._auth_token_request()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 270, in _auth_token_request
    return self.request(self.auth_url_token, method='post', data=post_data)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 176, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (400, u'invalid_grant')

**Comment by xybu** [comment]
This is more likely an issue if mk-fg/python-onedrive updated the API. Since 1.0-dev retires this dependency, could you try if the new version works for you (although it has only command-line interface at this stage)?
