### ISSUE TITLE
Unicode in filenames crashes application

### ISSUE THREAD

**Issue by kpj** [xybu/onedrive-d-old#73]
Hello,
I am using the latest version (438e93e3dc6053c3628773f5ed0131351c295053) of the 1.0-dev branch and get the following error when trying to sync some files:

```
Exception in thread syncer:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/kpj/onedrive-d/onedrive_d/daemon.py", line 674, in run
    self.merge_dir(entry)
  File "/home/kpj/onedrive-d/onedrive_d/daemon.py", line 631, in merge_dir
    entry_record = self.find_entry(parent_path = local_path, name = name)
  File "/home/kpj/onedrive-d/onedrive_d/daemon.py", line 494, in find_entry
    return find_entry(self.cursor, kwargs)
  File "/home/kpj/onedrive-d/onedrive_d/daemon.py", line 75, in find_entry
    cursor.execute('SELECT * FROM entries WHERE ' + ' AND '.join(wheres), criteria)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcfc' in position 12: surrogates not allowed

Exception in thread worker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/kpj/onedrive-d/onedrive_d/daemon.py", line 410, in run
    local_path = row['local_path'])
  File "/home/kpj/onedrive-d/onedrive_d/live_api.py", line 276, in put
    ret = r.json()
  File "/usr/lib/python3.4/site-packages/requests-2.4.3-py3.4.egg/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

Exception in thread worker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/kpj/onedrive-d/onedrive_d/daemon.py", line 410, in run
    local_path = row['local_path'])
  File "/home/kpj/onedrive-d/onedrive_d/live_api.py", line 276, in put
    ret = r.json()
  File "/usr/lib/python3.4/site-packages/requests-2.4.3-py3.4.egg/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

Afterwards, syncing just stops. This means that I cannot sync any files as opendrive-d always crashes.
Am I doing something wrong, or is there any fix to this problem?

I also noticed that there seem to be (maybe) related issues:
- https://github.com/xybu/onedrive-d/issues/70
- https://github.com/xybu/onedrive-d/issues/44

As the error message seems quite different from mine, I did not investigate them any further.

Do you have any idea what could be the reason for completely crashing on these specific filenames?

**Comment by xybu** [comment]
Hi,

I guess your system language is not UTF-8 encoded? Although I don't know the exact file name that caused the problem, I guess it contains some char that is encoded to something else, or is simply disallowed, when treated in UTF-8.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by kpj** [comment]
What exactly do you mean? My locale is as follows:

```
$ locale
LANG=en_US.utf8
LC_CTYPE=de_DE.utf8
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

I cannot check the filename because onedrive-d doesn't show it to me. But even if it finds an invalid filename, why is it crashing and not syncing anymore?

**Comment by xybu** [comment]
(python thinks) One of your file names has this char http://www.fileformat.info/info/unicode/char/dcfc/index.htm
and raises an exception that onedrive-d doesn't expect.

Let me think about how to deal with it.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by xybu** [comment]
Finally I found a workaround that may be used directly:
https://github.com/hsoft/dupeguru/commit/42be49da834ae5a25104d8c769e4011497b562a6

The idea is to rename the file for you to get rid of that character. By in one Python issue I read some time ago this char may have special use. So removing this char may have negative effect on that file.

**Comment by kpj** [comment]
Wouldn't it then make sense to not crash, but simply ignore the file?

**Comment by xybu** [comment]
For this situation I think the program should do the following:
1. Ignore the file
2. Tell the user something is wrong with that file name, and ask for renaming.

Anything else?

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by kpj** [comment]
Sounds good. Maybe it would be a good idea to store any such errors in a persistent log-file?

**Comment by xybu** [comment]
Any idea how I can reproduce the exception? I don't know how to make a file with name containing invalid Unicode char. If I can reproduce it I can figure out where to add the exception handling code.

**Comment by antonio-gil** [comment]
I don't know if this helps: https://stackoverflow.com/questions/6274670/write-unicode-content-and-unicode-file-name-in-windows (At least to have a hint)

**Comment by xybu** [comment]
For commit e88ab18b75ad73ab786d094d320718485b6a6594, change lines 204-208 of `od_worker_thread.py` from

``` python
        try:
            is_exist = os.path.exists(local_path)
        except UnicodeEncodeError:
            self.logger.error('Failed to stat entry "%s". Path is not Unicode.', local_path)
            return
```

to

``` python
        try:
            is_exist = os.path.exists(local_path)
        except UnicodeEncodeError:
            is_exist = os.path.exists(local_path.decode('utf-8').encode(sys.getfilesystemencoding())
```

and see if program crashes. If not then we find a solution.

**Comment by ewann** [comment]
@kpj 
I'm doing a review of long-open issues in onedrive-d. Did the last proposal from xybu fix solve this for you?
thanks

**Comment by kpj** [comment]
(Un)fortunately, I resolved the problem by simply renaming the conflicting files and thus wasn't able to check whether the proposal changed anything.

I might be able to try out some weird filenames later.

(which branch should I test it on? future?)
