### ISSUE TITLE
Hidden directories crash application

### ISSUE THREAD

**Issue by kpj** [xybu/onedrive-d-old#74]
Hello,
I am using the latest version (438e93e3dc6053c3628773f5ed0131351c295053) of the 1.0-dev branch and get the following error when trying to sync hidden directories:

```
[2014-10-09T17:15:12+0200] syncer   ERROR: "request_parameter_invalid: The operation couldn't be completed because the requested folder name, '.git' isn't supported. A folder name must not start or end with '.', must not contain any unprintable characters or contain any of the following characters: '\', '/', ':', ';', '*', '<', '>', '|', '?'."
Exception in thread syncer:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/kpj/onedrive-d/onedrive_d/daemon.py", line 674, in run
    self.merge_dir(entry)
  File "/home/kpj/onedrive-d/onedrive_d/daemon.py", line 640, in merge_dir
    self.remote_mkdir(local_path, name, remote_path)
  File "/home/kpj/onedrive-d/onedrive_d/daemon.py", line 481, in remote_mkdir
    self.enqueue(parent_path + name + '/', nd['id'])
TypeError: 'NoneType' object is not subscriptable
```

While the error message nicely explains the problem, I don't understand why this is crashing the whole program.
This should be easily fixable, right? (Or am I missing something?)

**Comment by xybu** [comment]
This nice error message is returned by OneDrive server, not onedrive-d... The best we can do is to add it to ignore list...

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by kpj** [comment]
Wouldn't it then make sense to add a generic `.*` to "ignore_list.txt"?

**Comment by xybu** [comment]
Yes this addition is necessary.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone
