### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by msunela** [xybu/onedrive-d-old#84]
Quite soon after the start of the main.py, inotify and both worker threads die, because of database locking error. Here's the traceback:

``` python
Exception in thread inotify:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 277, in run
    self.on_task_created(row)
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 195, in on_task_created
    self.cursor.execute('SELECT * FROM tasks WHERE task_type IN ("get", "put") AND local_path=?', (path + name,))
sqlite3.OperationalError: database is locked

Exception in thread worker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 405, in run
    self.do_postwork(row)
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 364, in do_postwork
    self.update_entry(new_info)
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 305, in update_entry
    update_entry(self.conn, entry)
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 109, in update_entry
    '(:parent_path, :name, :id, :parent_id, :type, :size, :client_updated_time, :status)', entry)
sqlite3.OperationalError: database is locked

Exception in thread worker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 419, in run
    self.do_postwork(row, update)
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 364, in do_postwork
    self.update_entry(new_info)
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 305, in update_entry
    update_entry(self.conn, entry)
  File "/home/share/onedrive-d/onedrive_d/daemon.py", line 109, in update_entry
    '(:parent_path, :name, :id, :parent_id, :type, :size, :client_updated_time, :status)', entry)
sqlite3.OperationalError: database is locked
```

**Comment by xybu** [comment]
If possible, could you send me the full output of the program? The db lock actually told me nothing about what happened.

I guess there is some other exception that kills one thread, and the db lock exceptions happen afterwards.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

-----Original Message-----

**Comment by msunela** [comment]
This is actually everything that was output to the console. I try to enable debug logging and see if there's something more. Anyway it seems that the program dies immediately after start, while still basically just starting the objects.

**Comment by xybu** [comment]
There are two threads alive: daemon and syncer. Without knowing what they were doing, or what was uncommitted, we can hardly solve the problem. By the way, the database is supposed to be a SQLite file in ~/.onedrive/, the lock should be in the same dir. Could you go there and see if there is anything useful left (for example, the content of the lock file, if it exists)?

**Comment by ljasinskipl** [comment]
I have the same problem. Full output:

```
/main.py --no-gui
[2014-11-01T22:32:12+0100] MainThread   INFO: there are 8 entries in the ignore list.
[2014-11-01T22:32:12+0100] daemon   DEBUG: start running.
[2014-11-01T22:32:14+0100] syncer   INFO: syncer starts running
[2014-11-01T22:32:14+0100] inotify  INFO: start running.
[2014-11-01T22:32:14+0100] worker-0 INFO: worker starts running.
[2014-11-01T22:32:14+0100] worker-1 INFO: worker starts running.
[2014-11-01T22:32:14+0100] daemon   INFO: restart the synchronizer.
[2014-11-01T22:32:14+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/
[2014-11-01T22:32:25+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Documents/
[2014-11-01T22:32:30+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Dokumenty/
[2014-11-01T22:32:33+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Faktury/
[2014-11-01T22:32:35+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/MBNP/
[2014-11-01T22:32:36+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/New folder/
[2014-11-01T22:32:38+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Nowy folder/
[2014-11-01T22:32:38+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Office Live Documents/
[2014-11-01T22:32:40+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Pictures/
[2014-11-01T22:32:41+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Public/
[2014-11-01T22:32:42+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/pzb/
[2014-11-01T22:32:43+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/sql backup/
[2014-11-01T22:32:45+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/studium/
[2014-11-01T22:32:47+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Dokumenty/Brydż/
[2014-11-01T22:32:49+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Dokumenty/Gosia/
[2014-11-01T22:32:50+0100] syncer   INFO: "/home/ljasinskipl/Cloud/onedrived/Dokumenty/Gosia/3e - dziwny sprawdzian.xlsx is older but conflicts can exist. Rename the local file.
[2014-11-01T22:32:50+0100] worker-0 DEBUG: I passed two locks.
[2014-11-01T22:32:50+0100] syncer   INFO: "/home/ljasinskipl/Cloud/onedrived/Dokumenty/Gosia/3f testy.xlsx is strictly newer. Upload it.
[2014-11-01T22:32:51+0100] syncer   DEBUG: Local file "/home/ljasinskipl/Cloud/onedrived/Dokumenty/Gosia/3e - dziwny sprawdzian (ljpl-sams720, older).xlsx" does not exist remotely. Upload it.
[2014-11-01T22:32:51+0100] worker-1 DEBUG: I passed two locks.
[2014-11-01T22:32:51+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Dokumenty/Organista/
[2014-11-01T22:32:52+0100] inotify  DEBUG: find_entry({'name': '3e - dziwny sprawdzian.xlsx', 'parent_path': '/home/ljasinskipl/Cloud/onedrived/Dokumenty/Gosia/'})
[2014-11-01T22:32:52+0100] inotify  INFO: ['/home/ljasinskipl/Cloud/onedrived/Dokumenty/Gosia/', 'MOVED_FROM', '3e - dziwny sprawdzian.xlsx']
[2014-11-01T22:32:52+0100] inotify  DEBUG: find_entry({'name': 'Gosia', 'parent_path': '/home/ljasinskipl/Cloud/onedrived/Dokumenty/'})
[2014-11-01T22:32:53+0100] inotify  INFO: ['/home/ljasinskipl/Cloud/onedrived/Dokumenty/Gosia/', 'MOVED_TO', '3e - dziwny sprawdzian (ljpl-sams720, older).xlsx']
Exception in thread worker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/ljasinskipl/bin/onedrive-d-dev/build/lib/onedrive_d/daemon.py", line 394, in run
    row = self.fetch_one_task()
  File "/home/ljasinskipl/bin/onedrive-d-dev/build/lib/onedrive_d/daemon.py", line 335, in fetch_one_task
    self.cursor.execute('SELECT * FROM tasks WHERE priority=1 ORDER BY date_created ASC LIMIT 1')
sqlite3.OperationalError: database is locked

[2014-11-01T22:33:02+0100] syncer   INFO: syncing /home/ljasinskipl/Cloud/onedrived/Dokumenty/Webmaster/
```

**Comment by dabioye** [comment]
Dealing with the same.
It started syncing initially but stopped. When I restarted the main client, it synced only the folder but nothing else. Now, when i restart the main.py, it just get stock at the database is locked message (see below).

root@localhost onedrive-d# ./onedrive_d/main.py
[2014-12-11T07:56:36+0400] MainThread   INFO: there are 0 entries in the ignore list.
[2014-12-11T07:56:36+0400] daemon   DEBUG: start running.
Exception in thread daemon:
Traceback (most recent call last):
  File "/usr/lib64/python3.3/threading.py", line 637, in _bootstrap_inner
    self.run()
  File "/home/dabioye/onedrive-d/onedrive_d/daemon.py", line 754, in run
    ''')
sqlite3.OperationalError: database is locked.

Any solution yet to this problem?

**Comment by Deathevn** [comment]
Hi, I tried to get your script running and ran into the same Error, but it is led by a different error.

```
[2014-12-17T13:31:40+0100] MainThread   INFO: there are 9 entries in the ignore list.
[2014-12-17T13:31:40+0100] daemon       DEBUG: start running.
[2014-12-17T13:31:40+0100] syncer       INFO: syncer starts running
[2014-12-17T13:31:40+0100] inotify      INFO: start running.
[2014-12-17T13:31:40+0100] worker-0     INFO: worker starts running.
[2014-12-17T13:31:41+0100] worker-1     INFO: worker starts running.
[2014-12-17T13:31:41+0100] daemon       INFO: restart the synchronizer.
[2014-12-17T13:31:41+0100] syncer       INFO: syncing /home/nadine/OneDrive/
[2014-12-17T13:31:42+0100] syncer       INFO: syncing /home/nadine/OneDrive/Angebote/
[2014-12-17T13:31:44+0100] syncer       INFO: syncing /home/nadine/OneDrive/Aufmaß/
[2014-12-17T13:31:44+0100] syncer       INFO: "/home/nadine/OneDrive/Aufmaß/Scan0005.PDF is newer but conflicts can exist. Rename the local file.
[2014-12-17T13:31:45+0100] syncer       DEBUG: Local file "/home/nadine/OneDrive/Aufmaß/Scan0005 (Nadine-Notebook, newer).PDF" does not exist remotely. Upload it.
[2014-12-17T13:31:45+0100] syncer       INFO: syncing /home/nadine/OneDrive/Bestellungen/
[2014-12-17T13:31:45+0100] worker-1     DEBUG: I passed two locks.
[2014-12-17T13:31:45+0100] worker-0     DEBUG: I passed two locks.
[2014-12-17T13:31:45+0100] worker-1     DEBUG: I get a row from tasks table.
[2014-12-17T13:31:45+0100] worker-1     INFO: Downloading "/home/nadine/OneDrive/Aufmaß/Scan0005.PDF".
[2014-12-17T13:31:45+0100] worker-0     DEBUG: I get a row from tasks table.
[2014-12-17T13:31:45+0100] worker-0     INFO: Uploading "/home/nadine/OneDrive/Aufmaß/Scan0005 (Nadine-Notebook, newer).PDF".
[2014-12-17T13:31:45+0100] syncer       INFO: "/home/nadine/OneDrive/Bestellungen/Best. GFA 5.9 Domiziel.odt is newer but conflicts can exist. Rename the local file.
[2014-12-17T13:31:47+0100] syncer       DEBUG: Local file "/home/nadine/OneDrive/Bestellungen/Best. GFA 5.9 Domiziel (Nadine-Notebook, newer).odt" does not exist remotely. Upload it.
[2014-12-17T13:31:48+0100] syncer       INFO: syncing /home/nadine/OneDrive/Bilder/
Exception in thread worker-0:
Traceback (most recent call last):
  File "/home/nadine/Programme/onedrive-d-1.0-dev/onedrive_d/daemon.py", line 419, in run
    self.do_postwork(row, update)
  File "/home/nadine/Programme/onedrive-d-1.0-dev/onedrive_d/daemon.py", line 373, in do_postwork
    os.utime(row['local_path'], (t, t))
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/nadine/Programme/onedrive-d-1.0-dev/onedrive_d/daemon.py", line 470, in run
    config.log.error('OSError {0}: {1}. Path: {2}.'.format(e.errno, e.strerr, e.filename))
AttributeError: 'PermissionError' object has no attribute 'strerr'

[2014-12-17T13:31:49+0100] worker-1     DEBUG: I passed two locks.
[2014-12-17T13:31:50+0100] worker-1     DEBUG: I get a row from tasks table.
[2014-12-17T13:31:50+0100] worker-1     INFO: Downloading "/home/nadine/OneDrive/Bestellungen/Best. GFA 5.9 Domiziel.odt".
[2014-12-17T13:31:53+0100] worker-1     DEBUG: I passed two locks.
[2014-12-17T13:31:54+0100] worker-1     DEBUG: I get a row from tasks table.
[2014-12-17T13:31:54+0100] worker-1     INFO: Downloading "/home/nadine/OneDrive/Bestellungen/Bestellung Vorlage.ott".
Exception in thread worker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/nadine/Programme/onedrive-d-1.0-dev/onedrive_d/daemon.py", line 405, in run
    self.do_postwork(row)
  File "/home/nadine/Programme/onedrive-d-1.0-dev/onedrive_d/daemon.py", line 364, in do_postwork
    self.update_entry(new_info)
  File "/home/nadine/Programme/onedrive-d-1.0-dev/onedrive_d/daemon.py", line 305, in update_entry
    update_entry(self.conn, entry)
  File "/home/nadine/Programme/onedrive-d-1.0-dev/onedrive_d/daemon.py", line 109, in update_entry
    '(:parent_path, :name, :id, :parent_id, :type, :size, :client_updated_time, :status)', entry)
sqlite3.OperationalError: database is locked

```

Running the script again syncs only the folder structure but isn't downloading any files.
Hope you will find the error.

(Kubuntu 14.10)

**Comment by evanbattle** [comment]
Adding a timeout to each of the sqlite connection lines in daemon.py seems to resolve this:

self.conn = sqlite3.connect(DAEMON_DB_PATH, isolation_level = None, timeout=30)

**Comment by guyromb** [comment]
I found a possible bug:
line 109 in daemon.py = When there are files with very long names (non english / html string) it will have problems with the database. therefore, timeout increasing won't help in this case.
e.g. this "entry" input to the database:

{'description': '', 'name': 'דוח חדש גרפים.xlsx', 'from': {'name': 'Guy Rombaut', 'id': 'dbfe551b5e022418'}, 'status': 'get', 'parent_path': '/home/guyromb/OneDrive/Excel/', 'size': 17252, 'updated_time': '2015-02-13T17:28:09+0000', 'id': 'file.dbfe551b5e022418.DBFE551B5E022418!3035', 'upload_location': 'https://apis.live.net/v5.0/file.dbfe551b5e022418.DBFE551B5E022418!3035/content/', 'link': 'https://onedrive.live.com/redir.aspx?cid=dbfe551b5e022418&page=view&resid=DBFE551B5E022418!3035&parId=DBFE551B5E022418!2430', 'parent_id': 'folder.dbfe551b5e022418.DBFE551B5E022418!2430', 'is_embeddable': True, 'shared_with': {'access': 'Just me'}, 'type': 'file', 'client_updated_time': '2007-10-17T21:19:47+0000', 'comments_enabled': False, 'created_time': '2014-05-17T11:44:05+0000', 'source': 'https://bhjpfw.dm2302.livefilestore.com/.........dFeelVmYLX0M1pGP9bUTBYxH23nKuGzQ6RakiQVmNu4RqXp86JQHclEZ01shQrb6Q5DF_CNmslhpPveiK1HHq2jeg/%D7%93%D7%95%D7%97%20%D7%97%D7%93%D7%A9%20%D7%92%D7%A8%D7%A4%D7%99%D7%9D.xlsx?psid=1', 'comments_count': 0}

**Comment by xybu** [comment]
Honestly i don't know why this can happen. Code in "future" branch has a universal lock to force exclusivity on database access. I'll push my work in the past few hours when I go back home. GUI and real-time file system monitoring are not done yet, but other than that it should work. If possible I really appreciate it if you can see if the problem is reproducible on that version. I want that version to be as stable as possible.

Sent from my Windows Phone

**Comment by xybu** [comment]
Hopefully program in `future` branch solved it... Any beta test is appreciated.

**Comment by MM128** [comment]
I was having a similar issue in 1.0 and just installed the future branch. No luck. Still having both workers throw an exception related to locking the database. My errors are identical to msunela's and Deathevn's. Occasionally, I get one that is identical to ljasinskipl's.

Let me know if there's any more info that'll help.

**Comment by xybu** [comment]
What is weird is that for "future" branch there is no chance two threads access the same database simultaneously because one thread must wait for mutex lock to be released by another thread so as to grab the lock and proceed.

Could you double check if you are really in "future" branch? E.g., check if the content of  README.md is the same as the one on the web.

Sent from my Windows Phone

**Comment by MM128** [comment]
Oh, shit. Good call. I installed the 1.0 again.

**Comment by xybu** [comment]
Give me 5 min so I can push my local stuff to "future".

Sent from my Windows Phone

**Comment by MM128** [comment]
Sounds like a plan.

**Comment by MM128** [comment]
Just installed it (right one this time!). Running into problems in setting up objects. Here's the traceback:

```
[2015-02-25 19:02:54,244] DEBUG: thread_mgr: started.
[2015-02-25 19:02:54,245] DEBUG: MainThread: daemon started.
Traceback (most recent call last):
  File "/usr/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==1.0.0dev', 'console_scripts', 'onedrive-d')()
  File "/usr/lib/python3.3/site-packages/onedrive_d-1.0.0dev-py3.3.egg/onedrive_d/od_main.py", line 45, in main
  File "/usr/lib/python3.3/site-packages/onedrive_d-1.0.0dev-py3.3.egg/onedrive_d/od_daemon_cli.py", line 113, in start
  File "/usr/lib/python3.3/site-packages/onedrive_d-1.0.0dev-py3.3.egg/onedrive_d/od_daemon_cli.py", line 53, in create_workers
  File "/usr/lib/python3.3/site-packages/onedrive_d-1.0.0dev-py3.3.egg/onedrive_d/od_sqlite.py", line 35, in __init__
TypeError: 'uri' is an invalid keyword argument for this function
[2015-02-25 19:02:54,835] DEBUG: Dummy-2: cleaning up.
```

**Comment by guyromb** [comment]
Hi,

I am using the "future" branch for two days. Seems the problem was gone. Everything works great for now :) !

**Comment by xybu** [comment]
@MM128 The issue has been solved. Read #118.

**Comment by MM128** [comment]
Excellent. Everything's working perfectly. Thank you so much!

**Comment by ljasinskipl** [comment]
Everything working fine. Great job, xybu

**Comment by msunela** [comment]
Works now! Great!
