### ISSUE TITLE
OSError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by jvecino** [xybu/onedrive-d-old#93]
Hi,

Sorry for my bad english.

Every now and then i receive errors while synching. I have 70 gig. of data to synch but every 3 or 4 gigs i get error like this. 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] No such file or directory: '/home/vnc/onedrive/Camera Joao/video-2011-11-24-19-58-43.mp4'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] No such file or directory: '/home/vnc/onedrive/Videos/Img 0037-11.m4v'

**Comment by xybu** [comment]
In `future` branch (I plan to version it 1.1 or something), large files will be handled in smaller chunks. Things will go more smoothly.
