### ISSUE TITLE
Not all sub-folders are synched

### ISSUE THREAD

**Issue by esefrsv** [xybu/onedrive-d-old#95]
Most contents of  a folder is synched, but in the case where I have more than 3 layers of sub-folders, only the folders are created but their contents is not synched.

E.G:
- Folder1
  - File1_1
  - File1_2
- Folder2
  - Folder2_1
    - Folder2_1_1
      - File2_2
      - File2_3
  - File2_1

All folders are created, but only File1_1, File1_2 and File2_1 get synched. Folder2_1_1 remains empty.
Is there a limit to how many levels of sub-folders OneDrive-d can synch?

**Comment by esefrsv** [comment]
...and now I just removed my synched copy and rebooted the computer and the synch restarted.
Now it has synched all directories. Go figure!

I guess this can be closed.

**Comment by h4kuna** [comment]
I have the same problem, and output from cli is:

```
Exception in thread worker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/srv/storage/Programy/Linux/onedrive-d/onedrive_d/daemon.py", line 419, in run
    self.do_postwork(row, update)
  File "/srv/storage/Programy/Linux/onedrive-d/onedrive_d/daemon.py", line 364, in do_postwork
    self.update_entry(new_info)
  File "/srv/storage/Programy/Linux/onedrive-d/onedrive_d/daemon.py", line 305, in update_entry
    update_entry(self.conn, entry)
  File "/srv/storage/Programy/Linux/onedrive-d/onedrive_d/daemon.py", line 109, in update_entry
    '(:parent_path, :name, :id, :parent_id, :type, :size, :client_updated_time, :status)', entry)
sqlite3.OperationalError: database is locked

Exception in thread worker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/srv/storage/Programy/Linux/onedrive-d/onedrive_d/daemon.py", line 419, in run
    self.do_postwork(row, update)
  File "/srv/storage/Programy/Linux/onedrive-d/onedrive_d/daemon.py", line 364, in do_postwork
    self.update_entry(new_info)
  File "/srv/storage/Programy/Linux/onedrive-d/onedrive_d/daemon.py", line 305, in update_entry
    update_entry(self.conn, entry)
  File "/srv/storage/Programy/Linux/onedrive-d/onedrive_d/daemon.py", line 109, in update_entry
    '(:parent_path, :name, :id, :parent_id, :type, :size, :client_updated_time, :status)', entry)
sqlite3.OperationalError: database is locked
```

**Comment by xybu** [comment]
I suppose there is an exception occurred before them?

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by h4kuna** [comment]
I install this onedrive like is in manual (1.0-dev). Nothing abnormaly. Maybe my onedrive is already exists and used with another device (4GB)? It's new  18GB photos/videos what I want upload. Daemon is executed manualy. Connection is okay because directories are created and any files too (0.1 GB).

**Comment by Kenarso** [comment]
I have the same Problem.
onedrive-d sync all Folders and Sub-folders. But at the third level of sub-folder onedrive-d dont sync the files.
When I started onedrive in the terminal I dont get any error. But I cant see that the sync is closed after the end of the lowest sub-folder level.
Anyone an Idea?

**Comment by xybu** [comment]
Forgot which thread discussed the BFS algorithm in onedrive-d. But that no longer matters. The workers in `future` (ver > 1.0-dev) are way more robust.

**Comment by xybu** [comment]
#84 #111
